<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiKeyCredentials
{
    /**
     * String value for apcaApiKeyId.
     */
    public function getApcaApiKeyId(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apcaApiKeyId
     */
    public function equals(string $apcaApiKeyId): bool;
}
