<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Authentication;

use Core\Authentication\CoreAuth;
use TraderApiLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class ApiKeyManager extends CoreAuth implements ApiKeyCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('APCA-API-KEY-ID', $this->getApcaApiKeyId())->requiredNonEmpty());
    }

    /**
     * String value for apcaApiKeyId.
     */
    public function getApcaApiKeyId(): string
    {
        return $this->config['apcaApiKeyId'] ?? ConfigurationDefaults::APCA_API_KEY_ID;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apcaApiKeyId
     */
    public function equals(string $apcaApiKeyId): bool
    {
        return $apcaApiKeyId == $this->getApcaApiKeyId();
    }
}
