<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing ApiKey security credentials.
 */
class ApiKeyCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for ApiKeyCredentialsBuilder
     *
     * @param string $apcaApiKeyId
     */
    public static function init(string $apcaApiKeyId): self
    {
        return new self(['apcaApiKeyId' => $apcaApiKeyId]);
    }

    /**
     * Setter for ApcaApiKeyId.
     *
     * @param string $apcaApiKeyId
     *
     * @return $this
     */
    public function apcaApiKeyId(string $apcaApiKeyId): self
    {
        $this->config['apcaApiKeyId'] = $apcaApiKeyId;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
