<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Authentication;

use Core\Authentication\CoreAuth;
use TraderApiLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class ApiSecretManager extends CoreAuth implements ApiSecretCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(
            HeaderParam::init('APCA-API-SECRET-KEY', $this->getApcaApiSecretKey())->requiredNonEmpty()
        );
    }

    /**
     * String value for apcaApiSecretKey.
     */
    public function getApcaApiSecretKey(): string
    {
        return $this->config['apcaApiSecretKey'] ?? ConfigurationDefaults::APCA_API_SECRET_KEY;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apcaApiSecretKey
     */
    public function equals(string $apcaApiSecretKey): bool
    {
        return $apcaApiSecretKey == $this->getApcaApiSecretKey();
    }
}
