<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiSecretCredentials
{
    /**
     * String value for apcaApiSecretKey.
     */
    public function getApcaApiSecretKey(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apcaApiSecretKey
     */
    public function equals(string $apcaApiSecretKey): bool;
}
