<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing ApiSecret security credentials.
 */
class ApiSecretCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for ApiSecretCredentialsBuilder
     *
     * @param string $apcaApiSecretKey
     */
    public static function init(string $apcaApiSecretKey): self
    {
        return new self(['apcaApiSecretKey' => $apcaApiSecretKey]);
    }

    /**
     * Setter for ApcaApiSecretKey.
     *
     * @param string $apcaApiSecretKey
     *
     * @return $this
     */
    public function apcaApiSecretKey(string $apcaApiSecretKey): self
    {
        $this->config['apcaApiSecretKey'] = $apcaApiSecretKey;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
