<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\AccountNonTradeActivities;

/**
 * Builder for model AccountNonTradeActivities
 *
 * @see AccountNonTradeActivities
 */
class AccountNonTradeActivitiesBuilder
{
    /**
     * @var AccountNonTradeActivities
     */
    private $instance;

    private function __construct(AccountNonTradeActivities $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Non Trade Activities Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountNonTradeActivities());
    }

    /**
     * Sets activity type field.
     *
     * @param string|null $value
     */
    public function activityType(?string $value): self
    {
        $this->instance->setActivityType($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets date field.
     *
     * @param \DateTime|null $value
     */
    public function date(?\DateTime $value): self
    {
        $this->instance->setDate($value);
        return $this;
    }

    /**
     * Sets net amount field.
     *
     * @param string|null $value
     */
    public function netAmount(?string $value): self
    {
        $this->instance->setNetAmount($value);
        return $this;
    }

    /**
     * Sets symbol field.
     *
     * @param string|null $value
     */
    public function symbol(?string $value): self
    {
        $this->instance->setSymbol($value);
        return $this;
    }

    /**
     * Sets qty field.
     *
     * @param string|null $value
     */
    public function qty(?string $value): self
    {
        $this->instance->setQty($value);
        return $this;
    }

    /**
     * Sets per share amount field.
     *
     * @param string|null $value
     */
    public function perShareAmount(?string $value): self
    {
        $this->instance->setPerShareAmount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Account Non Trade Activities object.
     */
    public function build(): AccountNonTradeActivities
    {
        return CoreHelper::clone($this->instance);
    }
}
