<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\AccountConfigurations;

/**
 * Builder for model AccountConfigurations
 *
 * @see AccountConfigurations
 */
class AccountConfigurationsBuilder
{
    /**
     * @var AccountConfigurations
     */
    private $instance;

    private function __construct(AccountConfigurations $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Configurations Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountConfigurations());
    }

    /**
     * Sets dtbp check field.
     *
     * @param string|null $value
     */
    public function dtbpCheck(?string $value): self
    {
        $this->instance->setDtbpCheck($value);
        return $this;
    }

    /**
     * Sets trade confirm email field.
     *
     * @param string|null $value
     */
    public function tradeConfirmEmail(?string $value): self
    {
        $this->instance->setTradeConfirmEmail($value);
        return $this;
    }

    /**
     * Sets suspend trade field.
     *
     * @param bool|null $value
     */
    public function suspendTrade(?bool $value): self
    {
        $this->instance->setSuspendTrade($value);
        return $this;
    }

    /**
     * Sets no shorting field.
     *
     * @param bool|null $value
     */
    public function noShorting(?bool $value): self
    {
        $this->instance->setNoShorting($value);
        return $this;
    }

    /**
     * Sets fractional trading field.
     *
     * @param bool|null $value
     */
    public function fractionalTrading(?bool $value): self
    {
        $this->instance->setFractionalTrading($value);
        return $this;
    }

    /**
     * Sets max margin multiplier field.
     *
     * @param string|null $value
     */
    public function maxMarginMultiplier(?string $value): self
    {
        $this->instance->setMaxMarginMultiplier($value);
        return $this;
    }

    /**
     * Sets pdt check field.
     *
     * @param string|null $value
     */
    public function pdtCheck(?string $value): self
    {
        $this->instance->setPdtCheck($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Account Configurations object.
     */
    public function build(): AccountConfigurations
    {
        return CoreHelper::clone($this->instance);
    }
}
