<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\AccountTradingActivities;

/**
 * Builder for model AccountTradingActivities
 *
 * @see AccountTradingActivities
 */
class AccountTradingActivitiesBuilder
{
    /**
     * @var AccountTradingActivities
     */
    private $instance;

    private function __construct(AccountTradingActivities $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Trading Activities Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountTradingActivities());
    }

    /**
     * Sets activity type field.
     *
     * @param string|null $value
     */
    public function activityType(?string $value): self
    {
        $this->instance->setActivityType($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets cum qty field.
     *
     * @param string|null $value
     */
    public function cumQty(?string $value): self
    {
        $this->instance->setCumQty($value);
        return $this;
    }

    /**
     * Sets leaves qty field.
     *
     * @param string|null $value
     */
    public function leavesQty(?string $value): self
    {
        $this->instance->setLeavesQty($value);
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param string|null $value
     */
    public function price(?string $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Sets qty field.
     *
     * @param string|null $value
     */
    public function qty(?string $value): self
    {
        $this->instance->setQty($value);
        return $this;
    }

    /**
     * Sets side field.
     *
     * @param string|null $value
     */
    public function side(?string $value): self
    {
        $this->instance->setSide($value);
        return $this;
    }

    /**
     * Sets symbol field.
     *
     * @param string|null $value
     */
    public function symbol(?string $value): self
    {
        $this->instance->setSymbol($value);
        return $this;
    }

    /**
     * Sets transaction time field.
     *
     * @param \DateTime|null $value
     */
    public function transactionTime(?\DateTime $value): self
    {
        $this->instance->setTransactionTime($value);
        return $this;
    }

    /**
     * Sets order id field.
     *
     * @param string|null $value
     */
    public function orderId(?string $value): self
    {
        $this->instance->setOrderId($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets order status field.
     *
     * @param string|null $value
     */
    public function orderStatus(?string $value): self
    {
        $this->instance->setOrderStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Account Trading Activities object.
     */
    public function build(): AccountTradingActivities
    {
        return CoreHelper::clone($this->instance);
    }
}
