<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Account;

/**
 * Builder for model Account
 *
 * @see Account
 */
class AccountBuilder
{
    /**
     * @var Account
     */
    private $instance;

    private function __construct(Account $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Builder object.
     *
     * @param string $id
     * @param string $status
     */
    public static function init(string $id, string $status): self
    {
        return new self(new Account($id, $status));
    }

    /**
     * Sets account number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets cash field.
     *
     * @param string|null $value
     */
    public function cash(?string $value): self
    {
        $this->instance->setCash($value);
        return $this;
    }

    /**
     * Sets portfolio value field.
     *
     * @param string|null $value
     */
    public function portfolioValue(?string $value): self
    {
        $this->instance->setPortfolioValue($value);
        return $this;
    }

    /**
     * Sets pattern day trader field.
     *
     * @param bool|null $value
     */
    public function patternDayTrader(?bool $value): self
    {
        $this->instance->setPatternDayTrader($value);
        return $this;
    }

    /**
     * Sets trade suspended by user field.
     *
     * @param bool|null $value
     */
    public function tradeSuspendedByUser(?bool $value): self
    {
        $this->instance->setTradeSuspendedByUser($value);
        return $this;
    }

    /**
     * Sets trading blocked field.
     *
     * @param bool|null $value
     */
    public function tradingBlocked(?bool $value): self
    {
        $this->instance->setTradingBlocked($value);
        return $this;
    }

    /**
     * Sets transfers blocked field.
     *
     * @param bool|null $value
     */
    public function transfersBlocked(?bool $value): self
    {
        $this->instance->setTransfersBlocked($value);
        return $this;
    }

    /**
     * Sets account blocked field.
     *
     * @param bool|null $value
     */
    public function accountBlocked(?bool $value): self
    {
        $this->instance->setAccountBlocked($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets shorting enabled field.
     *
     * @param bool|null $value
     */
    public function shortingEnabled(?bool $value): self
    {
        $this->instance->setShortingEnabled($value);
        return $this;
    }

    /**
     * Sets long market value field.
     *
     * @param string|null $value
     */
    public function longMarketValue(?string $value): self
    {
        $this->instance->setLongMarketValue($value);
        return $this;
    }

    /**
     * Sets short market value field.
     *
     * @param string|null $value
     */
    public function shortMarketValue(?string $value): self
    {
        $this->instance->setShortMarketValue($value);
        return $this;
    }

    /**
     * Sets equity field.
     *
     * @param string|null $value
     */
    public function equity(?string $value): self
    {
        $this->instance->setEquity($value);
        return $this;
    }

    /**
     * Sets last equity field.
     *
     * @param string|null $value
     */
    public function lastEquity(?string $value): self
    {
        $this->instance->setLastEquity($value);
        return $this;
    }

    /**
     * Sets multiplier field.
     *
     * @param string|null $value
     */
    public function multiplier(?string $value): self
    {
        $this->instance->setMultiplier($value);
        return $this;
    }

    /**
     * Sets buying power field.
     *
     * @param string|null $value
     */
    public function buyingPower(?string $value): self
    {
        $this->instance->setBuyingPower($value);
        return $this;
    }

    /**
     * Sets initial margin field.
     *
     * @param string|null $value
     */
    public function initialMargin(?string $value): self
    {
        $this->instance->setInitialMargin($value);
        return $this;
    }

    /**
     * Sets maintenance margin field.
     *
     * @param string|null $value
     */
    public function maintenanceMargin(?string $value): self
    {
        $this->instance->setMaintenanceMargin($value);
        return $this;
    }

    /**
     * Sets sma field.
     *
     * @param string|null $value
     */
    public function sma(?string $value): self
    {
        $this->instance->setSma($value);
        return $this;
    }

    /**
     * Sets daytrade count field.
     *
     * @param int|null $value
     */
    public function daytradeCount(?int $value): self
    {
        $this->instance->setDaytradeCount($value);
        return $this;
    }

    /**
     * Sets last maintenance margin field.
     *
     * @param string|null $value
     */
    public function lastMaintenanceMargin(?string $value): self
    {
        $this->instance->setLastMaintenanceMargin($value);
        return $this;
    }

    /**
     * Sets daytrading buying power field.
     *
     * @param string|null $value
     */
    public function daytradingBuyingPower(?string $value): self
    {
        $this->instance->setDaytradingBuyingPower($value);
        return $this;
    }

    /**
     * Sets regt buying power field.
     *
     * @param string|null $value
     */
    public function regtBuyingPower(?string $value): self
    {
        $this->instance->setRegtBuyingPower($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Account object.
     */
    public function build(): Account
    {
        return CoreHelper::clone($this->instance);
    }
}
