<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\AddAssetToWatchlistRequest;

/**
 * Builder for model AddAssetToWatchlistRequest
 *
 * @see AddAssetToWatchlistRequest
 */
class AddAssetToWatchlistRequestBuilder
{
    /**
     * @var AddAssetToWatchlistRequest
     */
    private $instance;

    private function __construct(AddAssetToWatchlistRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Add Asset To Watchlist Request Builder object.
     */
    public static function init(): self
    {
        return new self(new AddAssetToWatchlistRequest());
    }

    /**
     * Sets symbol field.
     *
     * @param string|null $value
     */
    public function symbol(?string $value): self
    {
        $this->instance->setSymbol($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Add Asset To Watchlist Request object.
     */
    public function build(): AddAssetToWatchlistRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
