<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Assets;

/**
 * Builder for model Assets
 *
 * @see Assets
 */
class AssetsBuilder
{
    /**
     * @var Assets
     */
    private $instance;

    private function __construct(Assets $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Assets Builder object.
     *
     * @param string $id
     * @param string $class
     * @param string $exchange
     * @param string $symbol
     * @param string $name
     * @param string $status
     * @param bool $tradable
     * @param bool $marginable
     * @param bool $shortable
     * @param bool $easyToBorrow
     * @param bool $fractionable
     */
    public static function init(
        string $id,
        string $class,
        string $exchange,
        string $symbol,
        string $name,
        string $status,
        bool $tradable,
        bool $marginable,
        bool $shortable,
        bool $easyToBorrow,
        bool $fractionable
    ): self {
        return new self(new Assets(
            $id,
            $class,
            $exchange,
            $symbol,
            $name,
            $status,
            $tradable,
            $marginable,
            $shortable,
            $easyToBorrow,
            $fractionable
        ));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Assets object.
     */
    public function build(): Assets
    {
        return CoreHelper::clone($this->instance);
    }
}
