<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Calendar;

/**
 * Builder for model Calendar
 *
 * @see Calendar
 */
class CalendarBuilder
{
    /**
     * @var Calendar
     */
    private $instance;

    private function __construct(Calendar $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar Builder object.
     *
     * @param string $date
     * @param string $open
     * @param string $close
     * @param string $sessionOpen
     * @param string $sessionClose
     */
    public static function init(
        string $date,
        string $open,
        string $close,
        string $sessionOpen,
        string $sessionClose
    ): self {
        return new self(new Calendar($date, $open, $close, $sessionOpen, $sessionClose));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar object.
     */
    public function build(): Calendar
    {
        return CoreHelper::clone($this->instance);
    }
}
