<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\CanceledOrderResponse;

/**
 * Builder for model CanceledOrderResponse
 *
 * @see CanceledOrderResponse
 */
class CanceledOrderResponseBuilder
{
    /**
     * @var CanceledOrderResponse
     */
    private $instance;

    private function __construct(CanceledOrderResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Canceled Order Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CanceledOrderResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param int|null $value
     */
    public function status(?int $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Canceled Order Response object.
     */
    public function build(): CanceledOrderResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
