<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Clock;

/**
 * Builder for model Clock
 *
 * @see Clock
 */
class ClockBuilder
{
    /**
     * @var Clock
     */
    private $instance;

    private function __construct(Clock $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Clock Builder object.
     */
    public static function init(): self
    {
        return new self(new Clock());
    }

    /**
     * Sets timestamp field.
     *
     * @param \DateTime|null $value
     */
    public function timestamp(?\DateTime $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets is open field.
     *
     * @param bool|null $value
     */
    public function isOpen(?bool $value): self
    {
        $this->instance->setIsOpen($value);
        return $this;
    }

    /**
     * Sets next open field.
     *
     * @param \DateTime|null $value
     */
    public function nextOpen(?\DateTime $value): self
    {
        $this->instance->setNextOpen($value);
        return $this;
    }

    /**
     * Sets next close field.
     *
     * @param \DateTime|null $value
     */
    public function nextClose(?\DateTime $value): self
    {
        $this->instance->setNextClose($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Clock object.
     */
    public function build(): Clock
    {
        return CoreHelper::clone($this->instance);
    }
}
