<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Order;

/**
 * Builder for model Order
 *
 * @see Order
 */
class OrderBuilder
{
    /**
     * @var Order
     */
    private $instance;

    private function __construct(Order $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Builder object.
     *
     * @param string $symbol
     * @param string $type
     * @param string $side
     * @param string $timeInForce
     */
    public static function init(string $symbol, string $type, string $side, string $timeInForce): self
    {
        return new self(new Order($symbol, $type, $side, $timeInForce));
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets client order id field.
     *
     * @param string|null $value
     */
    public function clientOrderId(?string $value): self
    {
        $this->instance->setClientOrderId($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param \DateTime|null $value
     */
    public function updatedAt(?\DateTime $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Unsets updated at field.
     */
    public function unsetUpdatedAt(): self
    {
        $this->instance->unsetUpdatedAt();
        return $this;
    }

    /**
     * Sets submitted at field.
     *
     * @param \DateTime|null $value
     */
    public function submittedAt(?\DateTime $value): self
    {
        $this->instance->setSubmittedAt($value);
        return $this;
    }

    /**
     * Unsets submitted at field.
     */
    public function unsetSubmittedAt(): self
    {
        $this->instance->unsetSubmittedAt();
        return $this;
    }

    /**
     * Sets filled at field.
     *
     * @param \DateTime|null $value
     */
    public function filledAt(?\DateTime $value): self
    {
        $this->instance->setFilledAt($value);
        return $this;
    }

    /**
     * Unsets filled at field.
     */
    public function unsetFilledAt(): self
    {
        $this->instance->unsetFilledAt();
        return $this;
    }

    /**
     * Sets expired at field.
     *
     * @param \DateTime|null $value
     */
    public function expiredAt(?\DateTime $value): self
    {
        $this->instance->setExpiredAt($value);
        return $this;
    }

    /**
     * Unsets expired at field.
     */
    public function unsetExpiredAt(): self
    {
        $this->instance->unsetExpiredAt();
        return $this;
    }

    /**
     * Sets canceled at field.
     *
     * @param \DateTime|null $value
     */
    public function canceledAt(?\DateTime $value): self
    {
        $this->instance->setCanceledAt($value);
        return $this;
    }

    /**
     * Unsets canceled at field.
     */
    public function unsetCanceledAt(): self
    {
        $this->instance->unsetCanceledAt();
        return $this;
    }

    /**
     * Sets failed at field.
     *
     * @param \DateTime|null $value
     */
    public function failedAt(?\DateTime $value): self
    {
        $this->instance->setFailedAt($value);
        return $this;
    }

    /**
     * Unsets failed at field.
     */
    public function unsetFailedAt(): self
    {
        $this->instance->unsetFailedAt();
        return $this;
    }

    /**
     * Sets replaced at field.
     *
     * @param \DateTime|null $value
     */
    public function replacedAt(?\DateTime $value): self
    {
        $this->instance->setReplacedAt($value);
        return $this;
    }

    /**
     * Unsets replaced at field.
     */
    public function unsetReplacedAt(): self
    {
        $this->instance->unsetReplacedAt();
        return $this;
    }

    /**
     * Sets replaced by field.
     *
     * @param string|null $value
     */
    public function replacedBy(?string $value): self
    {
        $this->instance->setReplacedBy($value);
        return $this;
    }

    /**
     * Unsets replaced by field.
     */
    public function unsetReplacedBy(): self
    {
        $this->instance->unsetReplacedBy();
        return $this;
    }

    /**
     * Sets replaces field.
     *
     * @param string|null $value
     */
    public function replaces(?string $value): self
    {
        $this->instance->setReplaces($value);
        return $this;
    }

    /**
     * Unsets replaces field.
     */
    public function unsetReplaces(): self
    {
        $this->instance->unsetReplaces();
        return $this;
    }

    /**
     * Sets asset id field.
     *
     * @param string|null $value
     */
    public function assetId(?string $value): self
    {
        $this->instance->setAssetId($value);
        return $this;
    }

    /**
     * Sets asset class field.
     *
     * @param string|null $value
     */
    public function assetClass(?string $value): self
    {
        $this->instance->setAssetClass($value);
        return $this;
    }

    /**
     * Sets notional field.
     *
     * @param string|null $value
     */
    public function notional(?string $value): self
    {
        $this->instance->setNotional($value);
        return $this;
    }

    /**
     * Sets qty field.
     *
     * @param string|null $value
     */
    public function qty(?string $value): self
    {
        $this->instance->setQty($value);
        return $this;
    }

    /**
     * Sets filled qty field.
     *
     * @param string|null $value
     */
    public function filledQty(?string $value): self
    {
        $this->instance->setFilledQty($value);
        return $this;
    }

    /**
     * Sets filled avg price field.
     *
     * @param string|null $value
     */
    public function filledAvgPrice(?string $value): self
    {
        $this->instance->setFilledAvgPrice($value);
        return $this;
    }

    /**
     * Unsets filled avg price field.
     */
    public function unsetFilledAvgPrice(): self
    {
        $this->instance->unsetFilledAvgPrice();
        return $this;
    }

    /**
     * Sets order class field.
     *
     * @param string|null $value
     */
    public function orderClass(?string $value): self
    {
        $this->instance->setOrderClass($value);
        return $this;
    }

    /**
     * Sets order type field.
     *
     * @param string|null $value
     */
    public function orderType(?string $value): self
    {
        $this->instance->setOrderType($value);
        return $this;
    }

    /**
     * Sets limit price field.
     *
     * @param string|null $value
     */
    public function limitPrice(?string $value): self
    {
        $this->instance->setLimitPrice($value);
        return $this;
    }

    /**
     * Unsets limit price field.
     */
    public function unsetLimitPrice(): self
    {
        $this->instance->unsetLimitPrice();
        return $this;
    }

    /**
     * Sets stop price field.
     *
     * @param string|null $value
     */
    public function stopPrice(?string $value): self
    {
        $this->instance->setStopPrice($value);
        return $this;
    }

    /**
     * Unsets stop price field.
     */
    public function unsetStopPrice(): self
    {
        $this->instance->unsetStopPrice();
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets extended hours field.
     *
     * @param bool|null $value
     */
    public function extendedHours(?bool $value): self
    {
        $this->instance->setExtendedHours($value);
        return $this;
    }

    /**
     * Sets legs field.
     *
     * @param Order[]|null $value
     */
    public function legs(?array $value): self
    {
        $this->instance->setLegs($value);
        return $this;
    }

    /**
     * Unsets legs field.
     */
    public function unsetLegs(): self
    {
        $this->instance->unsetLegs();
        return $this;
    }

    /**
     * Sets trail percent field.
     *
     * @param string|null $value
     */
    public function trailPercent(?string $value): self
    {
        $this->instance->setTrailPercent($value);
        return $this;
    }

    /**
     * Sets trail price field.
     *
     * @param string|null $value
     */
    public function trailPrice(?string $value): self
    {
        $this->instance->setTrailPrice($value);
        return $this;
    }

    /**
     * Sets hwm field.
     *
     * @param string|null $value
     */
    public function hwm(?string $value): self
    {
        $this->instance->setHwm($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Order object.
     */
    public function build(): Order
    {
        return CoreHelper::clone($this->instance);
    }
}
