<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\PatchOrderRequest;

/**
 * Builder for model PatchOrderRequest
 *
 * @see PatchOrderRequest
 */
class PatchOrderRequestBuilder
{
    /**
     * @var PatchOrderRequest
     */
    private $instance;

    private function __construct(PatchOrderRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Patch Order Request Builder object.
     */
    public static function init(): self
    {
        return new self(new PatchOrderRequest());
    }

    /**
     * Sets qty field.
     *
     * @param string|null $value
     */
    public function qty(?string $value): self
    {
        $this->instance->setQty($value);
        return $this;
    }

    /**
     * Sets time in force field.
     *
     * @param string|null $value
     */
    public function timeInForce(?string $value): self
    {
        $this->instance->setTimeInForce($value);
        return $this;
    }

    /**
     * Sets limit price field.
     *
     * @param string|null $value
     */
    public function limitPrice(?string $value): self
    {
        $this->instance->setLimitPrice($value);
        return $this;
    }

    /**
     * Sets stop price field.
     *
     * @param string|null $value
     */
    public function stopPrice(?string $value): self
    {
        $this->instance->setStopPrice($value);
        return $this;
    }

    /**
     * Sets trail field.
     *
     * @param string|null $value
     */
    public function trail(?string $value): self
    {
        $this->instance->setTrail($value);
        return $this;
    }

    /**
     * Sets client order id field.
     *
     * @param string|null $value
     */
    public function clientOrderId(?string $value): self
    {
        $this->instance->setClientOrderId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Patch Order Request object.
     */
    public function build(): PatchOrderRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
