<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\PortfolioHistory;

/**
 * Builder for model PortfolioHistory
 *
 * @see PortfolioHistory
 */
class PortfolioHistoryBuilder
{
    /**
     * @var PortfolioHistory
     */
    private $instance;

    private function __construct(PortfolioHistory $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Portfolio History Builder object.
     */
    public static function init(): self
    {
        return new self(new PortfolioHistory());
    }

    /**
     * Sets timestamp field.
     *
     * @param int[]|null $value
     */
    public function timestamp(?array $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets equity field.
     *
     * @param float[]|null $value
     */
    public function equity(?array $value): self
    {
        $this->instance->setEquity($value);
        return $this;
    }

    /**
     * Sets profit loss field.
     *
     * @param float[]|null $value
     */
    public function profitLoss(?array $value): self
    {
        $this->instance->setProfitLoss($value);
        return $this;
    }

    /**
     * Sets profit loss pct field.
     *
     * @param float[]|null $value
     */
    public function profitLossPct(?array $value): self
    {
        $this->instance->setProfitLossPct($value);
        return $this;
    }

    /**
     * Sets base value field.
     *
     * @param float|null $value
     */
    public function baseValue(?float $value): self
    {
        $this->instance->setBaseValue($value);
        return $this;
    }

    /**
     * Sets timeframe field.
     *
     * @param string|null $value
     */
    public function timeframe(?string $value): self
    {
        $this->instance->setTimeframe($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Portfolio History object.
     */
    public function build(): PortfolioHistory
    {
        return CoreHelper::clone($this->instance);
    }
}
