<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Order;
use TraderApiLib\Models\PositionClosedReponse;

/**
 * Builder for model PositionClosedReponse
 *
 * @see PositionClosedReponse
 */
class PositionClosedReponseBuilder
{
    /**
     * @var PositionClosedReponse
     */
    private $instance;

    private function __construct(PositionClosedReponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Position Closed Reponse Builder object.
     *
     * @param string $symbol
     * @param string $status
     */
    public static function init(string $symbol, string $status): self
    {
        return new self(new PositionClosedReponse($symbol, $status));
    }

    /**
     * Sets body field.
     *
     * @param Order|null $value
     */
    public function body(?Order $value): self
    {
        $this->instance->setBody($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Position Closed Reponse object.
     */
    public function build(): PositionClosedReponse
    {
        return CoreHelper::clone($this->instance);
    }
}
