<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Position;

/**
 * Builder for model Position
 *
 * @see Position
 */
class PositionBuilder
{
    /**
     * @var Position
     */
    private $instance;

    private function __construct(Position $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Position Builder object.
     *
     * @param string $assetId
     * @param string $symbol
     * @param string $exchange
     * @param string $assetClass
     * @param string $avgEntryPrice
     * @param string $qty
     * @param string $side
     * @param string $marketValue
     * @param string $costBasis
     * @param string $unrealizedPl
     * @param string $unrealizedPlpc
     * @param string $unrealizedIntradayPl
     * @param string $unrealizedIntradayPlpc
     * @param string $currentPrice
     * @param string $lastdayPrice
     * @param string $changeToday
     * @param bool $assetMarginable
     */
    public static function init(
        string $assetId,
        string $symbol,
        string $exchange,
        string $assetClass,
        string $avgEntryPrice,
        string $qty,
        string $side,
        string $marketValue,
        string $costBasis,
        string $unrealizedPl,
        string $unrealizedPlpc,
        string $unrealizedIntradayPl,
        string $unrealizedIntradayPlpc,
        string $currentPrice,
        string $lastdayPrice,
        string $changeToday,
        bool $assetMarginable
    ): self {
        return new self(new Position(
            $assetId,
            $symbol,
            $exchange,
            $assetClass,
            $avgEntryPrice,
            $qty,
            $side,
            $marketValue,
            $costBasis,
            $unrealizedPl,
            $unrealizedPlpc,
            $unrealizedIntradayPl,
            $unrealizedIntradayPlpc,
            $currentPrice,
            $lastdayPrice,
            $changeToday,
            $assetMarginable
        ));
    }

    /**
     * Sets qty available field.
     *
     * @param string|null $value
     */
    public function qtyAvailable(?string $value): self
    {
        $this->instance->setQtyAvailable($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Position object.
     */
    public function build(): Position
    {
        return CoreHelper::clone($this->instance);
    }
}
