<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\PostWatchlistRequest;

/**
 * Builder for model PostWatchlistRequest
 *
 * @see PostWatchlistRequest
 */
class PostWatchlistRequestBuilder
{
    /**
     * @var PostWatchlistRequest
     */
    private $instance;

    private function __construct(PostWatchlistRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Post Watchlist Request Builder object.
     *
     * @param string $name
     */
    public static function init(string $name): self
    {
        return new self(new PostWatchlistRequest($name));
    }

    /**
     * Sets symbols field.
     *
     * @param array<string|null>|null $value
     */
    public function symbols(?array $value): self
    {
        $this->instance->setSymbols($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Post Watchlist Request object.
     */
    public function build(): PostWatchlistRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
