<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TraderApiLib\Models\Assets;
use TraderApiLib\Models\Watchlist;

/**
 * Builder for model Watchlist
 *
 * @see Watchlist
 */
class WatchlistBuilder
{
    /**
     * @var Watchlist
     */
    private $instance;

    private function __construct(Watchlist $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Watchlist Builder object.
     *
     * @param string $id
     * @param string $accountId
     * @param \DateTime $createdAt
     * @param \DateTime $updatedAt
     * @param string $name
     */
    public static function init(
        string $id,
        string $accountId,
        \DateTime $createdAt,
        \DateTime $updatedAt,
        string $name
    ): self {
        return new self(new Watchlist($id, $accountId, $createdAt, $updatedAt, $name));
    }

    /**
     * Sets assets field.
     *
     * @param Assets[]|null $value
     */
    public function assets(?array $value): self
    {
        $this->instance->setAssets($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Watchlist object.
     */
    public function build(): Watchlist
    {
        return CoreHelper::clone($this->instance);
    }
}
