<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Apis;

use Core\Authentication\Auth;
use CoreInterfaces\Core\Request\RequestMethod;
use TraderApiLib\Http\ApiResponse;
use TraderApiLib\Models\Account;

class AccountsApi extends BaseApi
{
    /**
     * Returns the account associated with the API key.
     *
     * @return ApiResponse Response from the API call
     */
    public function getAccount(): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/v2/account')
            ->auth(Auth::and('API_Key', 'API_Secret'));

        $_resHandler = $this->responseHandler()->type(Account::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
