<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Apis;

use Core\Authentication\Auth;
use CoreInterfaces\Core\Request\RequestMethod;
use TraderApiLib\Http\ApiResponse;
use TraderApiLib\Models\Clock;

class ClockApi extends BaseApi
{
    /**
     * The clock API serves the current market timestamp, whether or not the market is currently open, as
     * well as the times of the next market open and close.
     *
     * Returns the market clock.
     *
     * @return ApiResponse Response from the API call
     */
    public function getClock(): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/v2/clock')
            ->auth(Auth::and('API_Key', 'API_Secret'));

        $_resHandler = $this->responseHandler()->type(Clock::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
