<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

/**
 * The account configuration API provides custom configurations about your trading account settings.
 * These configurations control various allow you to modify settings to suit your trading needs.
 */
class AccountConfigurations implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $dtbpCheck;

    /**
     * @var string|null
     */
    private $tradeConfirmEmail;

    /**
     * @var bool|null
     */
    private $suspendTrade;

    /**
     * @var bool|null
     */
    private $noShorting;

    /**
     * @var bool|null
     */
    private $fractionalTrading;

    /**
     * @var string|null
     */
    private $maxMarginMultiplier;

    /**
     * @var string|null
     */
    private $pdtCheck;

    /**
     * Returns Dtbp Check.
     * both, entry, or exit. Controls Day Trading Margin Call (DTMC) checks.
     */
    public function getDtbpCheck(): ?string
    {
        return $this->dtbpCheck;
    }

    /**
     * Sets Dtbp Check.
     * both, entry, or exit. Controls Day Trading Margin Call (DTMC) checks.
     *
     * @maps dtbp_check
     * @factory \TraderApiLib\Models\DtbpCheck::checkValue
     */
    public function setDtbpCheck(?string $dtbpCheck): void
    {
        $this->dtbpCheck = $dtbpCheck;
    }

    /**
     * Returns Trade Confirm Email.
     * all or none. If none, emails for order fills are not sent.
     */
    public function getTradeConfirmEmail(): ?string
    {
        return $this->tradeConfirmEmail;
    }

    /**
     * Sets Trade Confirm Email.
     * all or none. If none, emails for order fills are not sent.
     *
     * @maps trade_confirm_email
     */
    public function setTradeConfirmEmail(?string $tradeConfirmEmail): void
    {
        $this->tradeConfirmEmail = $tradeConfirmEmail;
    }

    /**
     * Returns Suspend Trade.
     * If true, new orders are blocked.
     */
    public function getSuspendTrade(): ?bool
    {
        return $this->suspendTrade;
    }

    /**
     * Sets Suspend Trade.
     * If true, new orders are blocked.
     *
     * @maps suspend_trade
     */
    public function setSuspendTrade(?bool $suspendTrade): void
    {
        $this->suspendTrade = $suspendTrade;
    }

    /**
     * Returns No Shorting.
     * If true, account becomes long-only mode.
     */
    public function getNoShorting(): ?bool
    {
        return $this->noShorting;
    }

    /**
     * Sets No Shorting.
     * If true, account becomes long-only mode.
     *
     * @maps no_shorting
     */
    public function setNoShorting(?bool $noShorting): void
    {
        $this->noShorting = $noShorting;
    }

    /**
     * Returns Fractional Trading.
     * If true, account is able to participate in fractional trading
     */
    public function getFractionalTrading(): ?bool
    {
        return $this->fractionalTrading;
    }

    /**
     * Sets Fractional Trading.
     * If true, account is able to participate in fractional trading
     *
     * @maps fractional_trading
     */
    public function setFractionalTrading(?bool $fractionalTrading): void
    {
        $this->fractionalTrading = $fractionalTrading;
    }

    /**
     * Returns Max Margin Multiplier.
     * Can be "1" or "2"
     */
    public function getMaxMarginMultiplier(): ?string
    {
        return $this->maxMarginMultiplier;
    }

    /**
     * Sets Max Margin Multiplier.
     * Can be "1" or "2"
     *
     * @maps max_margin_multiplier
     */
    public function setMaxMarginMultiplier(?string $maxMarginMultiplier): void
    {
        $this->maxMarginMultiplier = $maxMarginMultiplier;
    }

    /**
     * Returns Pdt Check.
     */
    public function getPdtCheck(): ?string
    {
        return $this->pdtCheck;
    }

    /**
     * Sets Pdt Check.
     *
     * @maps pdt_check
     */
    public function setPdtCheck(?string $pdtCheck): void
    {
        $this->pdtCheck = $pdtCheck;
    }

    /**
     * Converts the AccountConfigurations object to a human-readable string representation.
     *
     * @return string The string representation of the AccountConfigurations object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AccountConfigurations',
            [
                'dtbpCheck' => $this->dtbpCheck,
                'tradeConfirmEmail' => $this->tradeConfirmEmail,
                'suspendTrade' => $this->suspendTrade,
                'noShorting' => $this->noShorting,
                'fractionalTrading' => $this->fractionalTrading,
                'maxMarginMultiplier' => $this->maxMarginMultiplier,
                'pdtCheck' => $this->pdtCheck,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'dtbp_check',
        'trade_confirm_email',
        'suspend_trade',
        'no_shorting',
        'fractional_trading',
        'max_margin_multiplier',
        'pdt_check'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->dtbpCheck)) {
            $json['dtbp_check']            = DtbpCheck::checkValue($this->dtbpCheck);
        }
        if (isset($this->tradeConfirmEmail)) {
            $json['trade_confirm_email']   = $this->tradeConfirmEmail;
        }
        if (isset($this->suspendTrade)) {
            $json['suspend_trade']         = $this->suspendTrade;
        }
        if (isset($this->noShorting)) {
            $json['no_shorting']           = $this->noShorting;
        }
        if (isset($this->fractionalTrading)) {
            $json['fractional_trading']    = $this->fractionalTrading;
        }
        if (isset($this->maxMarginMultiplier)) {
            $json['max_margin_multiplier'] = $this->maxMarginMultiplier;
        }
        if (isset($this->pdtCheck)) {
            $json['pdt_check']             = $this->pdtCheck;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
