<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;
use TraderApiLib\Utils\DateTimeHelper;

/**
 * The account API serves important information related to an account, including account status, funds
 * available for trade, funds available for withdrawal, and various flags relevant to an account’s
 * ability to trade. An account maybe be blocked for just for trades (trades_blocked flag) or for both
 * trades and transfers (account_blocked flag) if Alpaca identifies the account to engaging in any
 * suspicious activity. Also, in accordance with FINRA’s pattern day trading rule, an account may be
 * flagged for pattern day trading (pattern_day_trader flag), which would inhibit an account from
 * placing any further day-trades. Please note that cryptocurrencies are not eligible assets to be used
 * as collateral for margin accounts and will require the asset be traded using cash only.
 */
class Account implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string|null
     */
    private $accountNumber;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var string|null
     */
    private $cash;

    /**
     * @var string|null
     */
    private $portfolioValue;

    /**
     * @var bool|null
     */
    private $patternDayTrader;

    /**
     * @var bool|null
     */
    private $tradeSuspendedByUser;

    /**
     * @var bool|null
     */
    private $tradingBlocked;

    /**
     * @var bool|null
     */
    private $transfersBlocked;

    /**
     * @var bool|null
     */
    private $accountBlocked;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var bool|null
     */
    private $shortingEnabled;

    /**
     * @var string|null
     */
    private $longMarketValue;

    /**
     * @var string|null
     */
    private $shortMarketValue;

    /**
     * @var string|null
     */
    private $equity;

    /**
     * @var string|null
     */
    private $lastEquity;

    /**
     * @var string|null
     */
    private $multiplier;

    /**
     * @var string|null
     */
    private $buyingPower;

    /**
     * @var string|null
     */
    private $initialMargin;

    /**
     * @var string|null
     */
    private $maintenanceMargin;

    /**
     * @var string|null
     */
    private $sma;

    /**
     * @var int|null
     */
    private $daytradeCount;

    /**
     * @var string|null
     */
    private $lastMaintenanceMargin;

    /**
     * @var string|null
     */
    private $daytradingBuyingPower;

    /**
     * @var string|null
     */
    private $regtBuyingPower;

    /**
     * @param string $id
     * @param string $status
     */
    public function __construct(string $id, string $status)
    {
        $this->id = $id;
        $this->status = $status;
    }

    /**
     * Returns Id.
     * Account Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Account Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Account Number.
     * Account number.
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * Account number.
     *
     * @maps account_number
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Status.
     * An enum representing the various possible account status values.
     *
     * Most likely, the account status is ACTIVE unless there is any problem. The account status may get in
     * ACCOUNT_UPDATED when personal information is being updated from the dashboard, in which case you may
     * not be allowed trading for a short period of time until the change is approved.
     *
     * - ONBOARDING
     * The account is onboarding.
     * - SUBMISSION_FAILED
     * The account application submission failed for some reason.
     * - SUBMITTED
     * The account application has been submitted for review.
     * - ACCOUNT_UPDATED
     * The account information is being updated.
     * - APPROVAL_PENDING
     * The final account approval is pending.
     * - ACTIVE
     * The account is active for trading.
     * - REJECTED
     * The account application has been rejected.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * An enum representing the various possible account status values.
     *
     * Most likely, the account status is ACTIVE unless there is any problem. The account status may get in
     * ACCOUNT_UPDATED when personal information is being updated from the dashboard, in which case you may
     * not be allowed trading for a short period of time until the change is approved.
     *
     * - ONBOARDING
     * The account is onboarding.
     * - SUBMISSION_FAILED
     * The account application submission failed for some reason.
     * - SUBMITTED
     * The account application has been submitted for review.
     * - ACCOUNT_UPDATED
     * The account information is being updated.
     * - APPROVAL_PENDING
     * The final account approval is pending.
     * - ACTIVE
     * The account is active for trading.
     * - REJECTED
     * The account application has been rejected.
     *
     * @required
     * @maps status
     * @factory \TraderApiLib\Models\AccountStatus::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Currency.
     * USD
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * USD
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Cash.
     * Cash Balance
     */
    public function getCash(): ?string
    {
        return $this->cash;
    }

    /**
     * Sets Cash.
     * Cash Balance
     *
     * @maps cash
     */
    public function setCash(?string $cash): void
    {
        $this->cash = $cash;
    }

    /**
     * Returns Portfolio Value.
     * Total value of cash + holding positions (This field is deprecated. It is equivalent to the equity
     * field.)
     */
    public function getPortfolioValue(): ?string
    {
        return $this->portfolioValue;
    }

    /**
     * Sets Portfolio Value.
     * Total value of cash + holding positions (This field is deprecated. It is equivalent to the equity
     * field.)
     *
     * @maps portfolio_value
     */
    public function setPortfolioValue(?string $portfolioValue): void
    {
        $this->portfolioValue = $portfolioValue;
    }

    /**
     * Returns Pattern Day Trader.
     * Whether or not the account has been flagged as a pattern day trader
     */
    public function getPatternDayTrader(): ?bool
    {
        return $this->patternDayTrader;
    }

    /**
     * Sets Pattern Day Trader.
     * Whether or not the account has been flagged as a pattern day trader
     *
     * @maps pattern_day_trader
     */
    public function setPatternDayTrader(?bool $patternDayTrader): void
    {
        $this->patternDayTrader = $patternDayTrader;
    }

    /**
     * Returns Trade Suspended by User.
     * User setting. If true, the account is not allowed to place orders.
     */
    public function getTradeSuspendedByUser(): ?bool
    {
        return $this->tradeSuspendedByUser;
    }

    /**
     * Sets Trade Suspended by User.
     * User setting. If true, the account is not allowed to place orders.
     *
     * @maps trade_suspended_by_user
     */
    public function setTradeSuspendedByUser(?bool $tradeSuspendedByUser): void
    {
        $this->tradeSuspendedByUser = $tradeSuspendedByUser;
    }

    /**
     * Returns Trading Blocked.
     * If true, the account is not allowed to place orders.
     */
    public function getTradingBlocked(): ?bool
    {
        return $this->tradingBlocked;
    }

    /**
     * Sets Trading Blocked.
     * If true, the account is not allowed to place orders.
     *
     * @maps trading_blocked
     */
    public function setTradingBlocked(?bool $tradingBlocked): void
    {
        $this->tradingBlocked = $tradingBlocked;
    }

    /**
     * Returns Transfers Blocked.
     * If true, the account is not allowed to request money transfers.
     */
    public function getTransfersBlocked(): ?bool
    {
        return $this->transfersBlocked;
    }

    /**
     * Sets Transfers Blocked.
     * If true, the account is not allowed to request money transfers.
     *
     * @maps transfers_blocked
     */
    public function setTransfersBlocked(?bool $transfersBlocked): void
    {
        $this->transfersBlocked = $transfersBlocked;
    }

    /**
     * Returns Account Blocked.
     * If true, the account activity by user is prohibited.
     */
    public function getAccountBlocked(): ?bool
    {
        return $this->accountBlocked;
    }

    /**
     * Sets Account Blocked.
     * If true, the account activity by user is prohibited.
     *
     * @maps account_blocked
     */
    public function setAccountBlocked(?bool $accountBlocked): void
    {
        $this->accountBlocked = $accountBlocked;
    }

    /**
     * Returns Created At.
     * Timestamp this account was created at
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Timestamp this account was created at
     *
     * @maps created_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Shorting Enabled.
     * Flag to denote whether or not the account is permitted to short
     */
    public function getShortingEnabled(): ?bool
    {
        return $this->shortingEnabled;
    }

    /**
     * Sets Shorting Enabled.
     * Flag to denote whether or not the account is permitted to short
     *
     * @maps shorting_enabled
     */
    public function setShortingEnabled(?bool $shortingEnabled): void
    {
        $this->shortingEnabled = $shortingEnabled;
    }

    /**
     * Returns Long Market Value.
     * Real-time MtM value of all long positions held in the account
     */
    public function getLongMarketValue(): ?string
    {
        return $this->longMarketValue;
    }

    /**
     * Sets Long Market Value.
     * Real-time MtM value of all long positions held in the account
     *
     * @maps long_market_value
     */
    public function setLongMarketValue(?string $longMarketValue): void
    {
        $this->longMarketValue = $longMarketValue;
    }

    /**
     * Returns Short Market Value.
     * Real-time MtM value of all short positions held in the account
     */
    public function getShortMarketValue(): ?string
    {
        return $this->shortMarketValue;
    }

    /**
     * Sets Short Market Value.
     * Real-time MtM value of all short positions held in the account
     *
     * @maps short_market_value
     */
    public function setShortMarketValue(?string $shortMarketValue): void
    {
        $this->shortMarketValue = $shortMarketValue;
    }

    /**
     * Returns Equity.
     * Cash + long_market_value + short_market_value
     */
    public function getEquity(): ?string
    {
        return $this->equity;
    }

    /**
     * Sets Equity.
     * Cash + long_market_value + short_market_value
     *
     * @maps equity
     */
    public function setEquity(?string $equity): void
    {
        $this->equity = $equity;
    }

    /**
     * Returns Last Equity.
     * Equity as of previous trading day at 16:00:00 ET
     */
    public function getLastEquity(): ?string
    {
        return $this->lastEquity;
    }

    /**
     * Sets Last Equity.
     * Equity as of previous trading day at 16:00:00 ET
     *
     * @maps last_equity
     */
    public function setLastEquity(?string $lastEquity): void
    {
        $this->lastEquity = $lastEquity;
    }

    /**
     * Returns Multiplier.
     * Buying power multiplier that represents account margin classification; valid values 1 (standard
     * limited margin account with 1x buying power), 2 (reg T margin account with 2x intraday and overnight
     * buying power; this is the default for all non-PDT accounts with $2,000 or more equity), 4 (PDT
     * account with 4x intraday buying power and 2x reg T overnight buying power)
     */
    public function getMultiplier(): ?string
    {
        return $this->multiplier;
    }

    /**
     * Sets Multiplier.
     * Buying power multiplier that represents account margin classification; valid values 1 (standard
     * limited margin account with 1x buying power), 2 (reg T margin account with 2x intraday and overnight
     * buying power; this is the default for all non-PDT accounts with $2,000 or more equity), 4 (PDT
     * account with 4x intraday buying power and 2x reg T overnight buying power)
     *
     * @maps multiplier
     */
    public function setMultiplier(?string $multiplier): void
    {
        $this->multiplier = $multiplier;
    }

    /**
     * Returns Buying Power.
     * Current available $ buying power; If multiplier = 4, this is your daytrade buying power which is
     * calculated as (last_equity - (last) maintenance_margin) * 4; If multiplier = 2, buying_power =
     * max(equity – initial_margin,0) * 2; If multiplier = 1, buying_power = cash
     */
    public function getBuyingPower(): ?string
    {
        return $this->buyingPower;
    }

    /**
     * Sets Buying Power.
     * Current available $ buying power; If multiplier = 4, this is your daytrade buying power which is
     * calculated as (last_equity - (last) maintenance_margin) * 4; If multiplier = 2, buying_power =
     * max(equity – initial_margin,0) * 2; If multiplier = 1, buying_power = cash
     *
     * @maps buying_power
     */
    public function setBuyingPower(?string $buyingPower): void
    {
        $this->buyingPower = $buyingPower;
    }

    /**
     * Returns Initial Margin.
     * Reg T initial margin requirement (continuously updated value)
     */
    public function getInitialMargin(): ?string
    {
        return $this->initialMargin;
    }

    /**
     * Sets Initial Margin.
     * Reg T initial margin requirement (continuously updated value)
     *
     * @maps initial_margin
     */
    public function setInitialMargin(?string $initialMargin): void
    {
        $this->initialMargin = $initialMargin;
    }

    /**
     * Returns Maintenance Margin.
     * Maintenance margin requirement (continuously updated value)
     */
    public function getMaintenanceMargin(): ?string
    {
        return $this->maintenanceMargin;
    }

    /**
     * Sets Maintenance Margin.
     * Maintenance margin requirement (continuously updated value)
     *
     * @maps maintenance_margin
     */
    public function setMaintenanceMargin(?string $maintenanceMargin): void
    {
        $this->maintenanceMargin = $maintenanceMargin;
    }

    /**
     * Returns Sma.
     * Value of special memorandum account (will be used at a later date to provide additional
     * buying_power)
     */
    public function getSma(): ?string
    {
        return $this->sma;
    }

    /**
     * Sets Sma.
     * Value of special memorandum account (will be used at a later date to provide additional
     * buying_power)
     *
     * @maps sma
     */
    public function setSma(?string $sma): void
    {
        $this->sma = $sma;
    }

    /**
     * Returns Daytrade Count.
     * The current number of daytrades that have been made in the last 5 trading days (inclusive of today)
     */
    public function getDaytradeCount(): ?int
    {
        return $this->daytradeCount;
    }

    /**
     * Sets Daytrade Count.
     * The current number of daytrades that have been made in the last 5 trading days (inclusive of today)
     *
     * @maps daytrade_count
     */
    public function setDaytradeCount(?int $daytradeCount): void
    {
        $this->daytradeCount = $daytradeCount;
    }

    /**
     * Returns Last Maintenance Margin.
     * Your maintenance margin requirement on the previous trading day
     */
    public function getLastMaintenanceMargin(): ?string
    {
        return $this->lastMaintenanceMargin;
    }

    /**
     * Sets Last Maintenance Margin.
     * Your maintenance margin requirement on the previous trading day
     *
     * @maps last_maintenance_margin
     */
    public function setLastMaintenanceMargin(?string $lastMaintenanceMargin): void
    {
        $this->lastMaintenanceMargin = $lastMaintenanceMargin;
    }

    /**
     * Returns Daytrading Buying Power.
     * Your buying power for day trades (continuously updated value)
     */
    public function getDaytradingBuyingPower(): ?string
    {
        return $this->daytradingBuyingPower;
    }

    /**
     * Sets Daytrading Buying Power.
     * Your buying power for day trades (continuously updated value)
     *
     * @maps daytrading_buying_power
     */
    public function setDaytradingBuyingPower(?string $daytradingBuyingPower): void
    {
        $this->daytradingBuyingPower = $daytradingBuyingPower;
    }

    /**
     * Returns Regt Buying Power.
     * Your buying power under Regulation T (your excess equity - equity minus margin value - times your
     * margin multiplier)
     */
    public function getRegtBuyingPower(): ?string
    {
        return $this->regtBuyingPower;
    }

    /**
     * Sets Regt Buying Power.
     * Your buying power under Regulation T (your excess equity - equity minus margin value - times your
     * margin multiplier)
     *
     * @maps regt_buying_power
     */
    public function setRegtBuyingPower(?string $regtBuyingPower): void
    {
        $this->regtBuyingPower = $regtBuyingPower;
    }

    /**
     * Converts the Account object to a human-readable string representation.
     *
     * @return string The string representation of the Account object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Account',
            [
                'id' => $this->id,
                'accountNumber' => $this->accountNumber,
                'status' => $this->status,
                'currency' => $this->currency,
                'cash' => $this->cash,
                'portfolioValue' => $this->portfolioValue,
                'patternDayTrader' => $this->patternDayTrader,
                'tradeSuspendedByUser' => $this->tradeSuspendedByUser,
                'tradingBlocked' => $this->tradingBlocked,
                'transfersBlocked' => $this->transfersBlocked,
                'accountBlocked' => $this->accountBlocked,
                'createdAt' => $this->createdAt,
                'shortingEnabled' => $this->shortingEnabled,
                'longMarketValue' => $this->longMarketValue,
                'shortMarketValue' => $this->shortMarketValue,
                'equity' => $this->equity,
                'lastEquity' => $this->lastEquity,
                'multiplier' => $this->multiplier,
                'buyingPower' => $this->buyingPower,
                'initialMargin' => $this->initialMargin,
                'maintenanceMargin' => $this->maintenanceMargin,
                'sma' => $this->sma,
                'daytradeCount' => $this->daytradeCount,
                'lastMaintenanceMargin' => $this->lastMaintenanceMargin,
                'daytradingBuyingPower' => $this->daytradingBuyingPower,
                'regtBuyingPower' => $this->regtBuyingPower,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'account_number',
        'status',
        'currency',
        'cash',
        'portfolio_value',
        'pattern_day_trader',
        'trade_suspended_by_user',
        'trading_blocked',
        'transfers_blocked',
        'account_blocked',
        'created_at',
        'shorting_enabled',
        'long_market_value',
        'short_market_value',
        'equity',
        'last_equity',
        'multiplier',
        'buying_power',
        'initial_margin',
        'maintenance_margin',
        'sma',
        'daytrade_count',
        'last_maintenance_margin',
        'daytrading_buying_power',
        'regt_buying_power'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                          = $this->id;
        if (isset($this->accountNumber)) {
            $json['account_number']          = $this->accountNumber;
        }
        $json['status']                      = AccountStatus::checkValue($this->status);
        if (isset($this->currency)) {
            $json['currency']                = $this->currency;
        }
        if (isset($this->cash)) {
            $json['cash']                    = $this->cash;
        }
        if (isset($this->portfolioValue)) {
            $json['portfolio_value']         = $this->portfolioValue;
        }
        if (isset($this->patternDayTrader)) {
            $json['pattern_day_trader']      = $this->patternDayTrader;
        }
        if (isset($this->tradeSuspendedByUser)) {
            $json['trade_suspended_by_user'] = $this->tradeSuspendedByUser;
        }
        if (isset($this->tradingBlocked)) {
            $json['trading_blocked']         = $this->tradingBlocked;
        }
        if (isset($this->transfersBlocked)) {
            $json['transfers_blocked']       = $this->transfersBlocked;
        }
        if (isset($this->accountBlocked)) {
            $json['account_blocked']         = $this->accountBlocked;
        }
        if (isset($this->createdAt)) {
            $json['created_at']              = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        }
        if (isset($this->shortingEnabled)) {
            $json['shorting_enabled']        = $this->shortingEnabled;
        }
        if (isset($this->longMarketValue)) {
            $json['long_market_value']       = $this->longMarketValue;
        }
        if (isset($this->shortMarketValue)) {
            $json['short_market_value']      = $this->shortMarketValue;
        }
        if (isset($this->equity)) {
            $json['equity']                  = $this->equity;
        }
        if (isset($this->lastEquity)) {
            $json['last_equity']             = $this->lastEquity;
        }
        if (isset($this->multiplier)) {
            $json['multiplier']              = $this->multiplier;
        }
        if (isset($this->buyingPower)) {
            $json['buying_power']            = $this->buyingPower;
        }
        if (isset($this->initialMargin)) {
            $json['initial_margin']          = $this->initialMargin;
        }
        if (isset($this->maintenanceMargin)) {
            $json['maintenance_margin']      = $this->maintenanceMargin;
        }
        if (isset($this->sma)) {
            $json['sma']                     = $this->sma;
        }
        if (isset($this->daytradeCount)) {
            $json['daytrade_count']          = $this->daytradeCount;
        }
        if (isset($this->lastMaintenanceMargin)) {
            $json['last_maintenance_margin'] = $this->lastMaintenanceMargin;
        }
        if (isset($this->daytradingBuyingPower)) {
            $json['daytrading_buying_power'] = $this->daytradingBuyingPower;
        }
        if (isset($this->regtBuyingPower)) {
            $json['regt_buying_power']       = $this->regtBuyingPower;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
