<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;
use TraderApiLib\Utils\DateTimeHelper;

class AccountTradingActivities implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $activityType;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $cumQty;

    /**
     * @var string|null
     */
    private $leavesQty;

    /**
     * @var string|null
     */
    private $price;

    /**
     * @var string|null
     */
    private $qty;

    /**
     * @var string|null
     */
    private $side;

    /**
     * @var string|null
     */
    private $symbol;

    /**
     * @var \DateTime|null
     */
    private $transactionTime;

    /**
     * @var string|null
     */
    private $orderId;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $orderStatus;

    /**
     * Returns Activity Type.
     * - FILL
     * Order fills (both partial and full fills)
     *
     * - TRANS
     * Cash transactions (both CSD and CSW)
     *
     * - MISC
     * Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)
     *
     * - ACATC
     * ACATS IN/OUT (Cash)
     *
     * - ACATS
     * ACATS IN/OUT (Securities)
     *
     * - CFEE
     * Crypto fee
     *
     * - CSD
     * Cash deposit(+)
     *
     * - CSW
     * Cash withdrawal(-)
     *
     * - DIV
     * Dividends
     *
     * - DIVCGL
     * Dividend (capital gain long term)
     *
     * - DIVCGS
     * Dividend (capital gain short term)
     *
     * - DIVFEE
     * Dividend fee
     *
     * - DIVFT
     * Dividend adjusted (Foreign Tax Withheld)
     *
     * - DIVNRA
     * Dividend adjusted (NRA Withheld)
     *
     * - DIVROC
     * Dividend return of capital
     *
     * - DIVTW
     * Dividend adjusted (Tefra Withheld)
     *
     * - DIVTXEX
     * Dividend (tax exempt)
     *
     * - FEE
     * Fee denominated in USD
     *
     * - INT
     * Interest (credit/margin)
     *
     * - INTNRA
     * Interest adjusted (NRA Withheld)
     *
     * - INTTW
     * Interest adjusted (Tefra Withheld)
     *
     * - JNL
     * Journal entry
     *
     * - JNLC
     * Journal entry (cash)
     *
     * - JNLS
     * Journal entry (stock)
     *
     * - MA
     * Merger/Acquisition
     *
     * - NC
     * Name change
     *
     * - OPASN
     * Option assignment
     *
     * - OPEXP
     * Option expiration
     *
     * - OPXRC
     * Option exercise
     *
     * - PTC
     * Pass Thru Charge
     *
     * - PTR
     * Pass Thru Rebate
     *
     * - REORG
     * Reorg CA
     *
     * - SC
     * Symbol change
     *
     * - SSO
     * Stock spinoff
     *
     * - SSP
     * Stock split
     */
    public function getActivityType(): ?string
    {
        return $this->activityType;
    }

    /**
     * Sets Activity Type.
     * - FILL
     * Order fills (both partial and full fills)
     *
     * - TRANS
     * Cash transactions (both CSD and CSW)
     *
     * - MISC
     * Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)
     *
     * - ACATC
     * ACATS IN/OUT (Cash)
     *
     * - ACATS
     * ACATS IN/OUT (Securities)
     *
     * - CFEE
     * Crypto fee
     *
     * - CSD
     * Cash deposit(+)
     *
     * - CSW
     * Cash withdrawal(-)
     *
     * - DIV
     * Dividends
     *
     * - DIVCGL
     * Dividend (capital gain long term)
     *
     * - DIVCGS
     * Dividend (capital gain short term)
     *
     * - DIVFEE
     * Dividend fee
     *
     * - DIVFT
     * Dividend adjusted (Foreign Tax Withheld)
     *
     * - DIVNRA
     * Dividend adjusted (NRA Withheld)
     *
     * - DIVROC
     * Dividend return of capital
     *
     * - DIVTW
     * Dividend adjusted (Tefra Withheld)
     *
     * - DIVTXEX
     * Dividend (tax exempt)
     *
     * - FEE
     * Fee denominated in USD
     *
     * - INT
     * Interest (credit/margin)
     *
     * - INTNRA
     * Interest adjusted (NRA Withheld)
     *
     * - INTTW
     * Interest adjusted (Tefra Withheld)
     *
     * - JNL
     * Journal entry
     *
     * - JNLC
     * Journal entry (cash)
     *
     * - JNLS
     * Journal entry (stock)
     *
     * - MA
     * Merger/Acquisition
     *
     * - NC
     * Name change
     *
     * - OPASN
     * Option assignment
     *
     * - OPEXP
     * Option expiration
     *
     * - OPXRC
     * Option exercise
     *
     * - PTC
     * Pass Thru Charge
     *
     * - PTR
     * Pass Thru Rebate
     *
     * - REORG
     * Reorg CA
     *
     * - SC
     * Symbol change
     *
     * - SSO
     * Stock spinoff
     *
     * - SSP
     * Stock split
     *
     * @maps activity_type
     * @factory \TraderApiLib\Models\ActivityType::checkValue
     */
    public function setActivityType(?string $activityType): void
    {
        $this->activityType = $activityType;
    }

    /**
     * Returns Id.
     * An id for the activity. Always in “::” format. Can be sent as page_token in requests to facilitate
     * the paging of results.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * An id for the activity. Always in “::” format. Can be sent as page_token in requests to facilitate
     * the paging of results.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Cum Qty.
     * The cumulative quantity of shares involved in the execution.
     */
    public function getCumQty(): ?string
    {
        return $this->cumQty;
    }

    /**
     * Sets Cum Qty.
     * The cumulative quantity of shares involved in the execution.
     *
     * @maps cum_qty
     */
    public function setCumQty(?string $cumQty): void
    {
        $this->cumQty = $cumQty;
    }

    /**
     * Returns Leaves Qty.
     * For partially_filled orders, the quantity of shares that are left to be filled.
     */
    public function getLeavesQty(): ?string
    {
        return $this->leavesQty;
    }

    /**
     * Sets Leaves Qty.
     * For partially_filled orders, the quantity of shares that are left to be filled.
     *
     * @maps leaves_qty
     */
    public function setLeavesQty(?string $leavesQty): void
    {
        $this->leavesQty = $leavesQty;
    }

    /**
     * Returns Price.
     * The per-share price that the trade was executed at.
     */
    public function getPrice(): ?string
    {
        return $this->price;
    }

    /**
     * Sets Price.
     * The per-share price that the trade was executed at.
     *
     * @maps price
     */
    public function setPrice(?string $price): void
    {
        $this->price = $price;
    }

    /**
     * Returns Qty.
     * The number of shares involved in the trade execution.
     */
    public function getQty(): ?string
    {
        return $this->qty;
    }

    /**
     * Sets Qty.
     * The number of shares involved in the trade execution.
     *
     * @maps qty
     */
    public function setQty(?string $qty): void
    {
        $this->qty = $qty;
    }

    /**
     * Returns Side.
     * buy or sell
     */
    public function getSide(): ?string
    {
        return $this->side;
    }

    /**
     * Sets Side.
     * buy or sell
     *
     * @maps side
     */
    public function setSide(?string $side): void
    {
        $this->side = $side;
    }

    /**
     * Returns Symbol.
     * The symbol of the security being traded.
     */
    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * The symbol of the security being traded.
     *
     * @maps symbol
     */
    public function setSymbol(?string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Transaction Time.
     * The time at which the execution occurred.
     */
    public function getTransactionTime(): ?\DateTime
    {
        return $this->transactionTime;
    }

    /**
     * Sets Transaction Time.
     * The time at which the execution occurred.
     *
     * @maps transaction_time
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTransactionTime(?\DateTime $transactionTime): void
    {
        $this->transactionTime = $transactionTime;
    }

    /**
     * Returns Order Id.
     * The id for the order that filled.
     */
    public function getOrderId(): ?string
    {
        return $this->orderId;
    }

    /**
     * Sets Order Id.
     * The id for the order that filled.
     *
     * @maps order_id
     */
    public function setOrderId(?string $orderId): void
    {
        $this->orderId = $orderId;
    }

    /**
     * Returns Type.
     * fill or partial_fill
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * fill or partial_fill
     *
     * @maps type
     * @factory \TraderApiLib\Models\Type::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Order Status.
     * An order executed through Alpaca can experience several status changes during its lifecycle. The
     * most common statuses are described in detail below:
     *
     * - new
     * The order has been received by Alpaca, and routed to exchanges for execution. This is the usual
     * initial state of an order.
     *
     * - partially_filled
     * The order has been partially filled.
     *
     * - filled
     * The order has been filled, and no further updates will occur for the order.
     *
     * - done_for_day
     * The order is done executing for the day, and will not receive further updates until the next
     * trading day.
     *
     * - canceled
     * The order has been canceled, and no further updates will occur for the order. This can be either
     * due to a cancel request by the user, or the order has been canceled by the exchanges due to its time-
     * in-force.
     *
     * - expired
     * The order has expired, and no further updates will occur for the order.
     *
     * - replaced
     * The order was replaced by another order, or was updated due to a market event such as corporate
     * action.
     *
     * - pending_cancel
     * The order is waiting to be canceled.
     *
     * - pending_replace
     * The order is waiting to be replaced by another order. The order will reject cancel request while
     * in this state.
     *
     * Less common states are described below. Note that these states only occur on very rare occasions,
     * and most users will likely never see their orders reach these states:
     *
     * - accepted
     * The order has been received by Alpaca, but hasn’t yet been routed to the execution venue. This
     * could be seen often out side of trading session hours.
     *
     * - pending_new
     * The order has been received by Alpaca, and routed to the exchanges, but has not yet been accepted
     * for execution. This state only occurs on rare occasions.
     *
     * - accepted_for_bidding
     * The order has been received by exchanges, and is evaluated for pricing. This state only occurs on
     * rare occasions.
     *
     * - stopped
     * The order has been stopped, and a trade is guaranteed for the order, usually at a stated price or
     * better, but has not yet occurred. This state only occurs on rare occasions.
     *
     * - rejected
     * The order has been rejected, and no further updates will occur for the order. This state occurs on
     * rare occasions and may occur based on various conditions decided by the exchanges.
     *
     * - suspended
     * The order has been suspended, and is not eligible for trading. This state only occurs on rare
     * occasions.
     *
     * - calculated
     * The order has been completed for the day (either filled or done for day), but remaining settlement
     * calculations are still pending. This state only occurs on rare occasions.
     *
     *
     * An order may be canceled through the API up until the point it reaches a state of either filled,
     * canceled, or expired.
     */
    public function getOrderStatus(): ?string
    {
        return $this->orderStatus;
    }

    /**
     * Sets Order Status.
     * An order executed through Alpaca can experience several status changes during its lifecycle. The
     * most common statuses are described in detail below:
     *
     * - new
     * The order has been received by Alpaca, and routed to exchanges for execution. This is the usual
     * initial state of an order.
     *
     * - partially_filled
     * The order has been partially filled.
     *
     * - filled
     * The order has been filled, and no further updates will occur for the order.
     *
     * - done_for_day
     * The order is done executing for the day, and will not receive further updates until the next
     * trading day.
     *
     * - canceled
     * The order has been canceled, and no further updates will occur for the order. This can be either
     * due to a cancel request by the user, or the order has been canceled by the exchanges due to its time-
     * in-force.
     *
     * - expired
     * The order has expired, and no further updates will occur for the order.
     *
     * - replaced
     * The order was replaced by another order, or was updated due to a market event such as corporate
     * action.
     *
     * - pending_cancel
     * The order is waiting to be canceled.
     *
     * - pending_replace
     * The order is waiting to be replaced by another order. The order will reject cancel request while
     * in this state.
     *
     * Less common states are described below. Note that these states only occur on very rare occasions,
     * and most users will likely never see their orders reach these states:
     *
     * - accepted
     * The order has been received by Alpaca, but hasn’t yet been routed to the execution venue. This
     * could be seen often out side of trading session hours.
     *
     * - pending_new
     * The order has been received by Alpaca, and routed to the exchanges, but has not yet been accepted
     * for execution. This state only occurs on rare occasions.
     *
     * - accepted_for_bidding
     * The order has been received by exchanges, and is evaluated for pricing. This state only occurs on
     * rare occasions.
     *
     * - stopped
     * The order has been stopped, and a trade is guaranteed for the order, usually at a stated price or
     * better, but has not yet occurred. This state only occurs on rare occasions.
     *
     * - rejected
     * The order has been rejected, and no further updates will occur for the order. This state occurs on
     * rare occasions and may occur based on various conditions decided by the exchanges.
     *
     * - suspended
     * The order has been suspended, and is not eligible for trading. This state only occurs on rare
     * occasions.
     *
     * - calculated
     * The order has been completed for the day (either filled or done for day), but remaining settlement
     * calculations are still pending. This state only occurs on rare occasions.
     *
     *
     * An order may be canceled through the API up until the point it reaches a state of either filled,
     * canceled, or expired.
     *
     * @maps order_status
     * @factory \TraderApiLib\Models\OrderStatus::checkValue
     */
    public function setOrderStatus(?string $orderStatus): void
    {
        $this->orderStatus = $orderStatus;
    }

    /**
     * Converts the AccountTradingActivities object to a human-readable string representation.
     *
     * @return string The string representation of the AccountTradingActivities object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AccountTradingActivities',
            [
                'activityType' => $this->activityType,
                'id' => $this->id,
                'cumQty' => $this->cumQty,
                'leavesQty' => $this->leavesQty,
                'price' => $this->price,
                'qty' => $this->qty,
                'side' => $this->side,
                'symbol' => $this->symbol,
                'transactionTime' => $this->transactionTime,
                'orderId' => $this->orderId,
                'type' => $this->type,
                'orderStatus' => $this->orderStatus,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'activity_type',
        'id',
        'cum_qty',
        'leaves_qty',
        'price',
        'qty',
        'side',
        'symbol',
        'transaction_time',
        'order_id',
        'type',
        'order_status'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->activityType)) {
            $json['activity_type']    = ActivityType::checkValue($this->activityType);
        }
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->cumQty)) {
            $json['cum_qty']          = $this->cumQty;
        }
        if (isset($this->leavesQty)) {
            $json['leaves_qty']       = $this->leavesQty;
        }
        if (isset($this->price)) {
            $json['price']            = $this->price;
        }
        if (isset($this->qty)) {
            $json['qty']              = $this->qty;
        }
        if (isset($this->side)) {
            $json['side']             = $this->side;
        }
        if (isset($this->symbol)) {
            $json['symbol']           = $this->symbol;
        }
        if (isset($this->transactionTime)) {
            $json['transaction_time'] = DateTimeHelper::toRfc3339DateTime($this->transactionTime);
        }
        if (isset($this->orderId)) {
            $json['order_id']         = $this->orderId;
        }
        if (isset($this->type)) {
            $json['type']             = Type::checkValue($this->type);
        }
        if (isset($this->orderStatus)) {
            $json['order_status']     = OrderStatus::checkValue($this->orderStatus);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
