<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * An enum representing the various possible account status values.
 *
 * Most likely, the account status is ACTIVE unless there is any problem. The account status may get in
 * ACCOUNT_UPDATED when personal information is being updated from the dashboard, in which case you may
 * not be allowed trading for a short period of time until the change is approved.
 *
 * - ONBOARDING
 * The account is onboarding.
 * - SUBMISSION_FAILED
 * The account application submission failed for some reason.
 * - SUBMITTED
 * The account application has been submitted for review.
 * - ACCOUNT_UPDATED
 * The account information is being updated.
 * - APPROVAL_PENDING
 * The final account approval is pending.
 * - ACTIVE
 * The account is active for trading.
 * - REJECTED
 * The account application has been rejected.
 */
class AccountStatus
{
    public const ONBOARDING = 'ONBOARDING';

    public const SUBMISSION_FAILED = 'SUBMISSION_FAILED';

    public const SUBMITTED = 'SUBMITTED';

    public const ACCOUNT_UPDATED = 'ACCOUNT_UPDATED';

    public const APPROVAL_PENDING = 'APPROVAL_PENDING';

    public const ACTIVE = 'ACTIVE';

    public const REJECTED = 'REJECTED';

    private const _ALL_VALUES = [
        self::ONBOARDING,
        self::SUBMISSION_FAILED,
        self::SUBMITTED,
        self::ACCOUNT_UPDATED,
        self::APPROVAL_PENDING,
        self::ACTIVE,
        self::REJECTED
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AccountStatus.");
    }
}
