<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;
use TraderApiLib\Utils\DateTimeHelper;

class AccountNonTradeActivities implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $activityType;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var \DateTime|null
     */
    private $date;

    /**
     * @var string|null
     */
    private $netAmount;

    /**
     * @var string|null
     */
    private $symbol;

    /**
     * @var string|null
     */
    private $qty;

    /**
     * @var string|null
     */
    private $perShareAmount;

    /**
     * Returns Activity Type.
     * - FILL
     * Order fills (both partial and full fills)
     *
     * - TRANS
     * Cash transactions (both CSD and CSW)
     *
     * - MISC
     * Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)
     *
     * - ACATC
     * ACATS IN/OUT (Cash)
     *
     * - ACATS
     * ACATS IN/OUT (Securities)
     *
     * - CFEE
     * Crypto fee
     *
     * - CSD
     * Cash deposit(+)
     *
     * - CSW
     * Cash withdrawal(-)
     *
     * - DIV
     * Dividends
     *
     * - DIVCGL
     * Dividend (capital gain long term)
     *
     * - DIVCGS
     * Dividend (capital gain short term)
     *
     * - DIVFEE
     * Dividend fee
     *
     * - DIVFT
     * Dividend adjusted (Foreign Tax Withheld)
     *
     * - DIVNRA
     * Dividend adjusted (NRA Withheld)
     *
     * - DIVROC
     * Dividend return of capital
     *
     * - DIVTW
     * Dividend adjusted (Tefra Withheld)
     *
     * - DIVTXEX
     * Dividend (tax exempt)
     *
     * - FEE
     * Fee denominated in USD
     *
     * - INT
     * Interest (credit/margin)
     *
     * - INTNRA
     * Interest adjusted (NRA Withheld)
     *
     * - INTTW
     * Interest adjusted (Tefra Withheld)
     *
     * - JNL
     * Journal entry
     *
     * - JNLC
     * Journal entry (cash)
     *
     * - JNLS
     * Journal entry (stock)
     *
     * - MA
     * Merger/Acquisition
     *
     * - NC
     * Name change
     *
     * - OPASN
     * Option assignment
     *
     * - OPEXP
     * Option expiration
     *
     * - OPXRC
     * Option exercise
     *
     * - PTC
     * Pass Thru Charge
     *
     * - PTR
     * Pass Thru Rebate
     *
     * - REORG
     * Reorg CA
     *
     * - SC
     * Symbol change
     *
     * - SSO
     * Stock spinoff
     *
     * - SSP
     * Stock split
     */
    public function getActivityType(): ?string
    {
        return $this->activityType;
    }

    /**
     * Sets Activity Type.
     * - FILL
     * Order fills (both partial and full fills)
     *
     * - TRANS
     * Cash transactions (both CSD and CSW)
     *
     * - MISC
     * Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)
     *
     * - ACATC
     * ACATS IN/OUT (Cash)
     *
     * - ACATS
     * ACATS IN/OUT (Securities)
     *
     * - CFEE
     * Crypto fee
     *
     * - CSD
     * Cash deposit(+)
     *
     * - CSW
     * Cash withdrawal(-)
     *
     * - DIV
     * Dividends
     *
     * - DIVCGL
     * Dividend (capital gain long term)
     *
     * - DIVCGS
     * Dividend (capital gain short term)
     *
     * - DIVFEE
     * Dividend fee
     *
     * - DIVFT
     * Dividend adjusted (Foreign Tax Withheld)
     *
     * - DIVNRA
     * Dividend adjusted (NRA Withheld)
     *
     * - DIVROC
     * Dividend return of capital
     *
     * - DIVTW
     * Dividend adjusted (Tefra Withheld)
     *
     * - DIVTXEX
     * Dividend (tax exempt)
     *
     * - FEE
     * Fee denominated in USD
     *
     * - INT
     * Interest (credit/margin)
     *
     * - INTNRA
     * Interest adjusted (NRA Withheld)
     *
     * - INTTW
     * Interest adjusted (Tefra Withheld)
     *
     * - JNL
     * Journal entry
     *
     * - JNLC
     * Journal entry (cash)
     *
     * - JNLS
     * Journal entry (stock)
     *
     * - MA
     * Merger/Acquisition
     *
     * - NC
     * Name change
     *
     * - OPASN
     * Option assignment
     *
     * - OPEXP
     * Option expiration
     *
     * - OPXRC
     * Option exercise
     *
     * - PTC
     * Pass Thru Charge
     *
     * - PTR
     * Pass Thru Rebate
     *
     * - REORG
     * Reorg CA
     *
     * - SC
     * Symbol change
     *
     * - SSO
     * Stock spinoff
     *
     * - SSP
     * Stock split
     *
     * @maps activity_type
     * @factory \TraderApiLib\Models\ActivityType::checkValue
     */
    public function setActivityType(?string $activityType): void
    {
        $this->activityType = $activityType;
    }

    /**
     * Returns Id.
     * An ID for the activity, always in “::” format. Can be sent as page_token in requests to facilitate
     * the paging of results.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * An ID for the activity, always in “::” format. Can be sent as page_token in requests to facilitate
     * the paging of results.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Date.
     * The date on which the activity occurred or on which the transaction associated with the activity
     * settled.
     */
    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * The date on which the activity occurred or on which the transaction associated with the activity
     * settled.
     *
     * @maps date
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDate(?\DateTime $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Net Amount.
     * The net amount of money (positive or negative) associated with the activity.
     */
    public function getNetAmount(): ?string
    {
        return $this->netAmount;
    }

    /**
     * Sets Net Amount.
     * The net amount of money (positive or negative) associated with the activity.
     *
     * @maps net_amount
     */
    public function setNetAmount(?string $netAmount): void
    {
        $this->netAmount = $netAmount;
    }

    /**
     * Returns Symbol.
     * The symbol of the security involved with the activity. Not present for all activity types.
     */
    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * The symbol of the security involved with the activity. Not present for all activity types.
     *
     * @maps symbol
     */
    public function setSymbol(?string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Qty.
     * For dividend activities, the number of shares that contributed to the payment. Not present for other
     * activity types.
     */
    public function getQty(): ?string
    {
        return $this->qty;
    }

    /**
     * Sets Qty.
     * For dividend activities, the number of shares that contributed to the payment. Not present for other
     * activity types.
     *
     * @maps qty
     */
    public function setQty(?string $qty): void
    {
        $this->qty = $qty;
    }

    /**
     * Returns Per Share Amount.
     * For dividend activities, the average amount paid per share. Not present for other activity types.
     */
    public function getPerShareAmount(): ?string
    {
        return $this->perShareAmount;
    }

    /**
     * Sets Per Share Amount.
     * For dividend activities, the average amount paid per share. Not present for other activity types.
     *
     * @maps per_share_amount
     */
    public function setPerShareAmount(?string $perShareAmount): void
    {
        $this->perShareAmount = $perShareAmount;
    }

    /**
     * Converts the AccountNonTradeActivities object to a human-readable string representation.
     *
     * @return string The string representation of the AccountNonTradeActivities object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AccountNonTradeActivities',
            [
                'activityType' => $this->activityType,
                'id' => $this->id,
                'date' => $this->date,
                'netAmount' => $this->netAmount,
                'symbol' => $this->symbol,
                'qty' => $this->qty,
                'perShareAmount' => $this->perShareAmount,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['activity_type', 'id', 'date', 'net_amount', 'symbol', 'qty', 'per_share_amount'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->activityType)) {
            $json['activity_type']    = ActivityType::checkValue($this->activityType);
        }
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->date)) {
            $json['date']             = DateTimeHelper::toRfc3339DateTime($this->date);
        }
        if (isset($this->netAmount)) {
            $json['net_amount']       = $this->netAmount;
        }
        if (isset($this->symbol)) {
            $json['symbol']           = $this->symbol;
        }
        if (isset($this->qty)) {
            $json['qty']              = $this->qty;
        }
        if (isset($this->perShareAmount)) {
            $json['per_share_amount'] = $this->perShareAmount;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
