<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * - FILL
 * Order fills (both partial and full fills)
 *
 * - TRANS
 * Cash transactions (both CSD and CSW)
 *
 * - MISC
 * Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)
 *
 * - ACATC
 * ACATS IN/OUT (Cash)
 *
 * - ACATS
 * ACATS IN/OUT (Securities)
 *
 * - CFEE
 * Crypto fee
 *
 * - CSD
 * Cash deposit(+)
 *
 * - CSW
 * Cash withdrawal(-)
 *
 * - DIV
 * Dividends
 *
 * - DIVCGL
 * Dividend (capital gain long term)
 *
 * - DIVCGS
 * Dividend (capital gain short term)
 *
 * - DIVFEE
 * Dividend fee
 *
 * - DIVFT
 * Dividend adjusted (Foreign Tax Withheld)
 *
 * - DIVNRA
 * Dividend adjusted (NRA Withheld)
 *
 * - DIVROC
 * Dividend return of capital
 *
 * - DIVTW
 * Dividend adjusted (Tefra Withheld)
 *
 * - DIVTXEX
 * Dividend (tax exempt)
 *
 * - FEE
 * Fee denominated in USD
 *
 * - INT
 * Interest (credit/margin)
 *
 * - INTNRA
 * Interest adjusted (NRA Withheld)
 *
 * - INTTW
 * Interest adjusted (Tefra Withheld)
 *
 * - JNL
 * Journal entry
 *
 * - JNLC
 * Journal entry (cash)
 *
 * - JNLS
 * Journal entry (stock)
 *
 * - MA
 * Merger/Acquisition
 *
 * - NC
 * Name change
 *
 * - OPASN
 * Option assignment
 *
 * - OPEXP
 * Option expiration
 *
 * - OPXRC
 * Option exercise
 *
 * - PTC
 * Pass Thru Charge
 *
 * - PTR
 * Pass Thru Rebate
 *
 * - REORG
 * Reorg CA
 *
 * - SC
 * Symbol change
 *
 * - SSO
 * Stock spinoff
 *
 * - SSP
 * Stock split
 */
class ActivityType
{
    public const FILL = 'FILL';

    public const TRANS = 'TRANS';

    public const MISC = 'MISC';

    public const ACATC = 'ACATC';

    public const ACATS = 'ACATS';

    public const CSD = 'CSD';

    public const CSW = 'CSW';

    public const DIV = 'DIV';

    public const DIVCGL = 'DIVCGL';

    public const DIVCGS = 'DIVCGS';

    public const DIVFEE = 'DIVFEE';

    public const DIVFT = 'DIVFT';

    public const DIVNRA = 'DIVNRA';

    public const DIVROC = 'DIVROC';

    public const DIVTW = 'DIVTW';

    public const DIVTXEX = 'DIVTXEX';

    public const INT = 'INT';

    public const INTNRA = 'INTNRA';

    public const INTTW = 'INTTW';

    public const JNL = 'JNL';

    public const JNLC = 'JNLC';

    public const JNLS = 'JNLS';

    public const MA = 'MA';

    public const NC = 'NC';

    public const OPASN = 'OPASN';

    public const OPEXP = 'OPEXP';

    public const OPXRC = 'OPXRC';

    public const PTC = 'PTC';

    public const PTR = 'PTR';

    public const REORG = 'REORG';

    public const SC = 'SC';

    public const SSO = 'SSO';

    public const SSP = 'SSP';

    public const CFEE = 'CFEE';

    public const FEE = 'FEE';

    private const _ALL_VALUES = [
        self::FILL,
        self::TRANS,
        self::MISC,
        self::ACATC,
        self::ACATS,
        self::CSD,
        self::CSW,
        self::DIV,
        self::DIVCGL,
        self::DIVCGS,
        self::DIVFEE,
        self::DIVFT,
        self::DIVNRA,
        self::DIVROC,
        self::DIVTW,
        self::DIVTXEX,
        self::INT,
        self::INTNRA,
        self::INTTW,
        self::JNL,
        self::JNLC,
        self::JNLS,
        self::MA,
        self::NC,
        self::OPASN,
        self::OPEXP,
        self::OPXRC,
        self::PTC,
        self::PTR,
        self::REORG,
        self::SC,
        self::SSO,
        self::SSP,
        self::CFEE,
        self::FEE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ActivityType.");
    }
}
