<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

/**
 * The assets API serves as the master list of assets available for trade and data consumption from
 * Alpaca. Assets are sorted by asset class, exchange and symbol. Some assets are only available for
 * data consumption via Polygon, and are not tradable with Alpaca. These assets will be marked with the
 * flag tradable=false.
 */
class Assets implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $class;

    /**
     * @var string
     */
    private $exchange;

    /**
     * @var string
     */
    private $symbol;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $status;

    /**
     * @var bool
     */
    private $tradable;

    /**
     * @var bool
     */
    private $marginable;

    /**
     * @var bool
     */
    private $shortable;

    /**
     * @var bool
     */
    private $easyToBorrow;

    /**
     * @var bool
     */
    private $fractionable;

    /**
     * @param string $id
     * @param string $class
     * @param string $exchange
     * @param string $symbol
     * @param string $name
     * @param string $status
     * @param bool $tradable
     * @param bool $marginable
     * @param bool $shortable
     * @param bool $easyToBorrow
     * @param bool $fractionable
     */
    public function __construct(
        string $id,
        string $class,
        string $exchange,
        string $symbol,
        string $name,
        string $status,
        bool $tradable,
        bool $marginable,
        bool $shortable,
        bool $easyToBorrow,
        bool $fractionable
    ) {
        $this->id = $id;
        $this->class = $class;
        $this->exchange = $exchange;
        $this->symbol = $symbol;
        $this->name = $name;
        $this->status = $status;
        $this->tradable = $tradable;
        $this->marginable = $marginable;
        $this->shortable = $shortable;
        $this->easyToBorrow = $easyToBorrow;
        $this->fractionable = $fractionable;
    }

    /**
     * Returns Id.
     * Asset ID
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Asset ID
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Class.
     * Represents what class of asset this is. Currently only supports `us_equity` or `crypto`
     */
    public function getClass(): string
    {
        return $this->class;
    }

    /**
     * Sets Class.
     * Represents what class of asset this is. Currently only supports `us_equity` or `crypto`
     *
     * @required
     * @maps class
     * @factory \TraderApiLib\Models\AssetClass::checkValue
     */
    public function setClass(string $class): void
    {
        $this->class = $class;
    }

    /**
     * Returns Exchange.
     * Represents the current exchanges Alpaca supports. List is currently:
     *
     * - AMEX
     * - ARCA
     * - BATS
     * - NYSE
     * - NASDAQ
     * - NYSEARCA
     * - OTC
     */
    public function getExchange(): string
    {
        return $this->exchange;
    }

    /**
     * Sets Exchange.
     * Represents the current exchanges Alpaca supports. List is currently:
     *
     * - AMEX
     * - ARCA
     * - BATS
     * - NYSE
     * - NASDAQ
     * - NYSEARCA
     * - OTC
     *
     * @required
     * @maps exchange
     * @factory \TraderApiLib\Models\Exchange::checkValue
     */
    public function setExchange(string $exchange): void
    {
        $this->exchange = $exchange;
    }

    /**
     * Returns Symbol.
     * The symbol of the asset
     */
    public function getSymbol(): string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * The symbol of the asset
     *
     * @required
     * @maps symbol
     */
    public function setSymbol(string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Name.
     * The official name of the asset
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The official name of the asset
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Status.
     * active or inactive
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * active or inactive
     *
     * @required
     * @maps status
     * @factory \TraderApiLib\Models\Status::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Tradable.
     * Asset is tradable on Alpaca or not
     */
    public function getTradable(): bool
    {
        return $this->tradable;
    }

    /**
     * Sets Tradable.
     * Asset is tradable on Alpaca or not
     *
     * @required
     * @maps tradable
     */
    public function setTradable(bool $tradable): void
    {
        $this->tradable = $tradable;
    }

    /**
     * Returns Marginable.
     * Asset is marginable or not
     */
    public function getMarginable(): bool
    {
        return $this->marginable;
    }

    /**
     * Sets Marginable.
     * Asset is marginable or not
     *
     * @required
     * @maps marginable
     */
    public function setMarginable(bool $marginable): void
    {
        $this->marginable = $marginable;
    }

    /**
     * Returns Shortable.
     * Asset is shortable or not
     */
    public function getShortable(): bool
    {
        return $this->shortable;
    }

    /**
     * Sets Shortable.
     * Asset is shortable or not
     *
     * @required
     * @maps shortable
     */
    public function setShortable(bool $shortable): void
    {
        $this->shortable = $shortable;
    }

    /**
     * Returns Easy to Borrow.
     * Asset is easy-to-borrow or not (filtering for easy_to_borrow = True is the best way to check whether
     * the name is currently available to short at Alpaca).
     */
    public function getEasyToBorrow(): bool
    {
        return $this->easyToBorrow;
    }

    /**
     * Sets Easy to Borrow.
     * Asset is easy-to-borrow or not (filtering for easy_to_borrow = True is the best way to check whether
     * the name is currently available to short at Alpaca).
     *
     * @required
     * @maps easy_to_borrow
     */
    public function setEasyToBorrow(bool $easyToBorrow): void
    {
        $this->easyToBorrow = $easyToBorrow;
    }

    /**
     * Returns Fractionable.
     * Asset is fractionable or not
     */
    public function getFractionable(): bool
    {
        return $this->fractionable;
    }

    /**
     * Sets Fractionable.
     * Asset is fractionable or not
     *
     * @required
     * @maps fractionable
     */
    public function setFractionable(bool $fractionable): void
    {
        $this->fractionable = $fractionable;
    }

    /**
     * Converts the Assets object to a human-readable string representation.
     *
     * @return string The string representation of the Assets object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Assets',
            [
                'id' => $this->id,
                'class' => $this->class,
                'exchange' => $this->exchange,
                'symbol' => $this->symbol,
                'name' => $this->name,
                'status' => $this->status,
                'tradable' => $this->tradable,
                'marginable' => $this->marginable,
                'shortable' => $this->shortable,
                'easyToBorrow' => $this->easyToBorrow,
                'fractionable' => $this->fractionable,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'class',
        'exchange',
        'symbol',
        'name',
        'status',
        'tradable',
        'marginable',
        'shortable',
        'easy_to_borrow',
        'fractionable'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']             = $this->id;
        $json['class']          = AssetClass::checkValue($this->class);
        $json['exchange']       = Exchange::checkValue($this->exchange);
        $json['symbol']         = $this->symbol;
        $json['name']           = $this->name;
        $json['status']         = Status::checkValue($this->status);
        $json['tradable']       = $this->tradable;
        $json['marginable']     = $this->marginable;
        $json['shortable']      = $this->shortable;
        $json['easy_to_borrow'] = $this->easyToBorrow;
        $json['fractionable']   = $this->fractionable;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
