<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

class Calendar implements \JsonSerializable
{
    /**
     * @var string
     */
    private $date;

    /**
     * @var string
     */
    private $open;

    /**
     * @var string
     */
    private $close;

    /**
     * @var string
     */
    private $sessionOpen;

    /**
     * @var string
     */
    private $sessionClose;

    /**
     * @param string $date
     * @param string $open
     * @param string $close
     * @param string $sessionOpen
     * @param string $sessionClose
     */
    public function __construct(string $date, string $open, string $close, string $sessionOpen, string $sessionClose)
    {
        $this->date = $date;
        $this->open = $open;
        $this->close = $close;
        $this->sessionOpen = $sessionOpen;
        $this->sessionClose = $sessionClose;
    }

    /**
     * Returns Date.
     * Date string in “%Y-%m-%d” format
     */
    public function getDate(): string
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * Date string in “%Y-%m-%d” format
     *
     * @required
     * @maps date
     */
    public function setDate(string $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Open.
     * The time the market opens at on this date in “%H:%M” format
     */
    public function getOpen(): string
    {
        return $this->open;
    }

    /**
     * Sets Open.
     * The time the market opens at on this date in “%H:%M” format
     *
     * @required
     * @maps open
     */
    public function setOpen(string $open): void
    {
        $this->open = $open;
    }

    /**
     * Returns Close.
     * The time the market closes at on this date in “%H:%M” format
     */
    public function getClose(): string
    {
        return $this->close;
    }

    /**
     * Sets Close.
     * The time the market closes at on this date in “%H:%M” format
     *
     * @required
     * @maps close
     */
    public function setClose(string $close): void
    {
        $this->close = $close;
    }

    /**
     * Returns Session Open.
     */
    public function getSessionOpen(): string
    {
        return $this->sessionOpen;
    }

    /**
     * Sets Session Open.
     *
     * @required
     * @maps session_open
     */
    public function setSessionOpen(string $sessionOpen): void
    {
        $this->sessionOpen = $sessionOpen;
    }

    /**
     * Returns Session Close.
     */
    public function getSessionClose(): string
    {
        return $this->sessionClose;
    }

    /**
     * Sets Session Close.
     *
     * @required
     * @maps session_close
     */
    public function setSessionClose(string $sessionClose): void
    {
        $this->sessionClose = $sessionClose;
    }

    /**
     * Converts the Calendar object to a human-readable string representation.
     *
     * @return string The string representation of the Calendar object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Calendar',
            [
                'date' => $this->date,
                'open' => $this->open,
                'close' => $this->close,
                'sessionOpen' => $this->sessionOpen,
                'sessionClose' => $this->sessionClose,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['date', 'open', 'close', 'session_open', 'session_close'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['date']          = $this->date;
        $json['open']          = $this->open;
        $json['close']         = $this->close;
        $json['session_open']  = $this->sessionOpen;
        $json['session_close'] = $this->sessionClose;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
