<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;
use TraderApiLib\Utils\DateTimeHelper;

class Clock implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $timestamp;

    /**
     * @var bool|null
     */
    private $isOpen;

    /**
     * @var \DateTime|null
     */
    private $nextOpen;

    /**
     * @var \DateTime|null
     */
    private $nextClose;

    /**
     * Returns Timestamp.
     * Current timestamp
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     * Current timestamp
     *
     * @maps timestamp
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimestamp(?\DateTime $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Is Open.
     * Whether or not the market is open
     */
    public function getIsOpen(): ?bool
    {
        return $this->isOpen;
    }

    /**
     * Sets Is Open.
     * Whether or not the market is open
     *
     * @maps is_open
     */
    public function setIsOpen(?bool $isOpen): void
    {
        $this->isOpen = $isOpen;
    }

    /**
     * Returns Next Open.
     * Next Market open timestamp
     */
    public function getNextOpen(): ?\DateTime
    {
        return $this->nextOpen;
    }

    /**
     * Sets Next Open.
     * Next Market open timestamp
     *
     * @maps next_open
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setNextOpen(?\DateTime $nextOpen): void
    {
        $this->nextOpen = $nextOpen;
    }

    /**
     * Returns Next Close.
     * Next market close timestamp
     */
    public function getNextClose(): ?\DateTime
    {
        return $this->nextClose;
    }

    /**
     * Sets Next Close.
     * Next market close timestamp
     *
     * @maps next_close
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setNextClose(?\DateTime $nextClose): void
    {
        $this->nextClose = $nextClose;
    }

    /**
     * Converts the Clock object to a human-readable string representation.
     *
     * @return string The string representation of the Clock object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Clock',
            [
                'timestamp' => $this->timestamp,
                'isOpen' => $this->isOpen,
                'nextOpen' => $this->nextOpen,
                'nextClose' => $this->nextClose,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['timestamp', 'is_open', 'next_open', 'next_close'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->timestamp)) {
            $json['timestamp']  = DateTimeHelper::toRfc3339DateTime($this->timestamp);
        }
        if (isset($this->isOpen)) {
            $json['is_open']    = $this->isOpen;
        }
        if (isset($this->nextOpen)) {
            $json['next_open']  = DateTimeHelper::toRfc3339DateTime($this->nextOpen);
        }
        if (isset($this->nextClose)) {
            $json['next_close'] = DateTimeHelper::toRfc3339DateTime($this->nextClose);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
