<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Represents the current exchanges Alpaca supports. List is currently:
 *
 * - AMEX
 * - ARCA
 * - BATS
 * - NYSE
 * - NASDAQ
 * - NYSEARCA
 * - OTC
 */
class Exchange
{
    public const AMEX = 'AMEX';

    public const ARCA = 'ARCA';

    public const BATS = 'BATS';

    public const NYSE = 'NYSE';

    public const NASDAQ = 'NASDAQ';

    public const NYSEARCA = 'NYSEARCA';

    public const OTC = 'OTC';

    private const _ALL_VALUES =
        [self::AMEX, self::ARCA, self::BATS, self::NYSE, self::NASDAQ, self::NYSEARCA, self::OTC];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Exchange.");
    }
}
