<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;
use TraderApiLib\Utils\DateTimeHelper;

/**
 * The Orders API allows a user to monitor, place and cancel their orders with Alpaca.
 *
 * Each order has a unique identifier provided by the client. This client-side unique order ID will be
 * automatically generated by the system if not provided by the client, and will be returned as part of
 * the order object along with the rest of the fields described below. Once an order is placed, it can
 * be queried using the client-side order ID to check the status.
 *
 * Updates on open orders at Alpaca will also be sent over the streaming interface, which is the
 * recommended method of maintaining order state.
 */
class Order implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $clientOrderId;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var array
     */
    private $updatedAt = [];

    /**
     * @var array
     */
    private $submittedAt = [];

    /**
     * @var array
     */
    private $filledAt = [];

    /**
     * @var array
     */
    private $expiredAt = [];

    /**
     * @var array
     */
    private $canceledAt = [];

    /**
     * @var array
     */
    private $failedAt = [];

    /**
     * @var array
     */
    private $replacedAt = [];

    /**
     * @var array
     */
    private $replacedBy = [];

    /**
     * @var array
     */
    private $replaces = [];

    /**
     * @var string|null
     */
    private $assetId;

    /**
     * @var string
     */
    private $symbol;

    /**
     * @var string|null
     */
    private $assetClass;

    /**
     * @var string|null
     */
    private $notional;

    /**
     * @var string|null
     */
    private $qty;

    /**
     * @var string|null
     */
    private $filledQty;

    /**
     * @var array
     */
    private $filledAvgPrice = [];

    /**
     * @var string|null
     */
    private $orderClass;

    /**
     * @var string|null
     */
    private $orderType;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $side;

    /**
     * @var string
     */
    private $timeInForce;

    /**
     * @var array
     */
    private $limitPrice = [];

    /**
     * @var array
     */
    private $stopPrice = [];

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var bool|null
     */
    private $extendedHours;

    /**
     * @var array
     */
    private $legs = [];

    /**
     * @var string|null
     */
    private $trailPercent;

    /**
     * @var string|null
     */
    private $trailPrice;

    /**
     * @var string|null
     */
    private $hwm;

    /**
     * @param string $symbol
     * @param string $type
     * @param string $side
     * @param string $timeInForce
     */
    public function __construct(string $symbol, string $type, string $side, string $timeInForce)
    {
        $this->symbol = $symbol;
        $this->type = $type;
        $this->side = $side;
        $this->timeInForce = $timeInForce;
    }

    /**
     * Returns Id.
     * Order ID
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Order ID
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Client Order Id.
     * Client unique order ID
     */
    public function getClientOrderId(): ?string
    {
        return $this->clientOrderId;
    }

    /**
     * Sets Client Order Id.
     * Client unique order ID
     *
     * @maps client_order_id
     */
    public function setClientOrderId(?string $clientOrderId): void
    {
        $this->clientOrderId = $clientOrderId;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @maps created_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): ?\DateTime
    {
        if (count($this->updatedAt) == 0) {
            return null;
        }
        return $this->updatedAt['value'];
    }

    /**
     * Sets Updated At.
     *
     * @maps updated_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt['value'] = $updatedAt;
    }

    /**
     * Unsets Updated At.
     */
    public function unsetUpdatedAt(): void
    {
        $this->updatedAt = [];
    }

    /**
     * Returns Submitted At.
     */
    public function getSubmittedAt(): ?\DateTime
    {
        if (count($this->submittedAt) == 0) {
            return null;
        }
        return $this->submittedAt['value'];
    }

    /**
     * Sets Submitted At.
     *
     * @maps submitted_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setSubmittedAt(?\DateTime $submittedAt): void
    {
        $this->submittedAt['value'] = $submittedAt;
    }

    /**
     * Unsets Submitted At.
     */
    public function unsetSubmittedAt(): void
    {
        $this->submittedAt = [];
    }

    /**
     * Returns Filled At.
     */
    public function getFilledAt(): ?\DateTime
    {
        if (count($this->filledAt) == 0) {
            return null;
        }
        return $this->filledAt['value'];
    }

    /**
     * Sets Filled At.
     *
     * @maps filled_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setFilledAt(?\DateTime $filledAt): void
    {
        $this->filledAt['value'] = $filledAt;
    }

    /**
     * Unsets Filled At.
     */
    public function unsetFilledAt(): void
    {
        $this->filledAt = [];
    }

    /**
     * Returns Expired At.
     */
    public function getExpiredAt(): ?\DateTime
    {
        if (count($this->expiredAt) == 0) {
            return null;
        }
        return $this->expiredAt['value'];
    }

    /**
     * Sets Expired At.
     *
     * @maps expired_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpiredAt(?\DateTime $expiredAt): void
    {
        $this->expiredAt['value'] = $expiredAt;
    }

    /**
     * Unsets Expired At.
     */
    public function unsetExpiredAt(): void
    {
        $this->expiredAt = [];
    }

    /**
     * Returns Canceled At.
     */
    public function getCanceledAt(): ?\DateTime
    {
        if (count($this->canceledAt) == 0) {
            return null;
        }
        return $this->canceledAt['value'];
    }

    /**
     * Sets Canceled At.
     *
     * @maps canceled_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCanceledAt(?\DateTime $canceledAt): void
    {
        $this->canceledAt['value'] = $canceledAt;
    }

    /**
     * Unsets Canceled At.
     */
    public function unsetCanceledAt(): void
    {
        $this->canceledAt = [];
    }

    /**
     * Returns Failed At.
     */
    public function getFailedAt(): ?\DateTime
    {
        if (count($this->failedAt) == 0) {
            return null;
        }
        return $this->failedAt['value'];
    }

    /**
     * Sets Failed At.
     *
     * @maps failed_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setFailedAt(?\DateTime $failedAt): void
    {
        $this->failedAt['value'] = $failedAt;
    }

    /**
     * Unsets Failed At.
     */
    public function unsetFailedAt(): void
    {
        $this->failedAt = [];
    }

    /**
     * Returns Replaced At.
     */
    public function getReplacedAt(): ?\DateTime
    {
        if (count($this->replacedAt) == 0) {
            return null;
        }
        return $this->replacedAt['value'];
    }

    /**
     * Sets Replaced At.
     *
     * @maps replaced_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setReplacedAt(?\DateTime $replacedAt): void
    {
        $this->replacedAt['value'] = $replacedAt;
    }

    /**
     * Unsets Replaced At.
     */
    public function unsetReplacedAt(): void
    {
        $this->replacedAt = [];
    }

    /**
     * Returns Replaced By.
     * The order ID that this order was replaced by
     */
    public function getReplacedBy(): ?string
    {
        if (count($this->replacedBy) == 0) {
            return null;
        }
        return $this->replacedBy['value'];
    }

    /**
     * Sets Replaced By.
     * The order ID that this order was replaced by
     *
     * @maps replaced_by
     */
    public function setReplacedBy(?string $replacedBy): void
    {
        $this->replacedBy['value'] = $replacedBy;
    }

    /**
     * Unsets Replaced By.
     * The order ID that this order was replaced by
     */
    public function unsetReplacedBy(): void
    {
        $this->replacedBy = [];
    }

    /**
     * Returns Replaces.
     * The order ID that this order replaces
     */
    public function getReplaces(): ?string
    {
        if (count($this->replaces) == 0) {
            return null;
        }
        return $this->replaces['value'];
    }

    /**
     * Sets Replaces.
     * The order ID that this order replaces
     *
     * @maps replaces
     */
    public function setReplaces(?string $replaces): void
    {
        $this->replaces['value'] = $replaces;
    }

    /**
     * Unsets Replaces.
     * The order ID that this order replaces
     */
    public function unsetReplaces(): void
    {
        $this->replaces = [];
    }

    /**
     * Returns Asset Id.
     * Asset ID
     */
    public function getAssetId(): ?string
    {
        return $this->assetId;
    }

    /**
     * Sets Asset Id.
     * Asset ID
     *
     * @maps asset_id
     */
    public function setAssetId(?string $assetId): void
    {
        $this->assetId = $assetId;
    }

    /**
     * Returns Symbol.
     * Asset symbol
     */
    public function getSymbol(): string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * Asset symbol
     *
     * @required
     * @maps symbol
     */
    public function setSymbol(string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Asset Class.
     * Represents what class of asset this is. Currently only supports `us_equity` or `crypto`
     */
    public function getAssetClass(): ?string
    {
        return $this->assetClass;
    }

    /**
     * Sets Asset Class.
     * Represents what class of asset this is. Currently only supports `us_equity` or `crypto`
     *
     * @maps asset_class
     * @factory \TraderApiLib\Models\AssetClass::checkValue
     */
    public function setAssetClass(?string $assetClass): void
    {
        $this->assetClass = $assetClass;
    }

    /**
     * Returns Notional.
     * Ordered notional amount. If entered, qty will be null. Can take up to 9 decimal points.
     */
    public function getNotional(): ?string
    {
        return $this->notional;
    }

    /**
     * Sets Notional.
     * Ordered notional amount. If entered, qty will be null. Can take up to 9 decimal points.
     *
     * @maps notional
     */
    public function setNotional(?string $notional): void
    {
        $this->notional = $notional;
    }

    /**
     * Returns Qty.
     * Ordered quantity. If entered, notional will be null. Can take up to 9 decimal points.
     */
    public function getQty(): ?string
    {
        return $this->qty;
    }

    /**
     * Sets Qty.
     * Ordered quantity. If entered, notional will be null. Can take up to 9 decimal points.
     *
     * @maps qty
     */
    public function setQty(?string $qty): void
    {
        $this->qty = $qty;
    }

    /**
     * Returns Filled Qty.
     * Filled quantity
     */
    public function getFilledQty(): ?string
    {
        return $this->filledQty;
    }

    /**
     * Sets Filled Qty.
     * Filled quantity
     *
     * @maps filled_qty
     */
    public function setFilledQty(?string $filledQty): void
    {
        $this->filledQty = $filledQty;
    }

    /**
     * Returns Filled Avg Price.
     * Filled average price
     */
    public function getFilledAvgPrice(): ?string
    {
        if (count($this->filledAvgPrice) == 0) {
            return null;
        }
        return $this->filledAvgPrice['value'];
    }

    /**
     * Sets Filled Avg Price.
     * Filled average price
     *
     * @maps filled_avg_price
     */
    public function setFilledAvgPrice(?string $filledAvgPrice): void
    {
        $this->filledAvgPrice['value'] = $filledAvgPrice;
    }

    /**
     * Unsets Filled Avg Price.
     * Filled average price
     */
    public function unsetFilledAvgPrice(): void
    {
        $this->filledAvgPrice = [];
    }

    /**
     * Returns Order Class.
     * This will either be the empty string "", "simple", "bracket", "oco", or "oto".
     */
    public function getOrderClass(): ?string
    {
        return $this->orderClass;
    }

    /**
     * Sets Order Class.
     * This will either be the empty string "", "simple", "bracket", "oco", or "oto".
     *
     * @maps order_class
     * @factory \TraderApiLib\Models\OrderClass::checkValue
     */
    public function setOrderClass(?string $orderClass): void
    {
        $this->orderClass = $orderClass;
    }

    /**
     * Returns Order Type.
     * Deprecated in favour of the field "type"
     */
    public function getOrderType(): ?string
    {
        return $this->orderType;
    }

    /**
     * Sets Order Type.
     * Deprecated in favour of the field "type"
     *
     * @maps order_type
     */
    public function setOrderType(?string $orderType): void
    {
        $this->orderType = $orderType;
    }

    /**
     * Returns Type.
     * Represents the types of orders Alpaca currently supports
     *
     * - market
     * - limit
     * - stop
     * - stop_limit
     * - trailing_stop
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Represents the types of orders Alpaca currently supports
     *
     * - market
     * - limit
     * - stop
     * - stop_limit
     * - trailing_stop
     *
     * @required
     * @maps type
     * @factory \TraderApiLib\Models\OrderType::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Side.
     * Represents which side this order was on:
     *
     * - buy
     * - sell
     */
    public function getSide(): string
    {
        return $this->side;
    }

    /**
     * Sets Side.
     * Represents which side this order was on:
     *
     * - buy
     * - sell
     *
     * @required
     * @maps side
     * @factory \TraderApiLib\Models\OrderSide::checkValue
     */
    public function setSide(string $side): void
    {
        $this->side = $side;
    }

    /**
     * Returns Time in Force.
     * Note: For Crypto Trading, Alpaca supports the following Time-In-Force designations: day, gtc, ioc
     * and fok. OPG and CLS are not supported.
     *
     * Alpaca supports the following Time-In-Force designations:
     *
     * - day
     * A day order is eligible for execution only on the day it is live. By default, the order is only
     * valid during Regular Trading Hours (9:30am - 4:00pm ET). If unfilled after the closing auction, it
     * is automatically canceled. If submitted after the close, it is queued and submitted the following
     * trading day. However, if marked as eligible for extended hours, the order can also execute during
     * supported extended hours.
     *
     * - gtc
     * The order is good until canceled. Non-marketable GTC limit orders are subject to price adjustments
     * to offset corporate actions affecting the issue. We do not currently support Do Not Reduce(DNR)
     * orders to opt out of such price adjustments.
     *
     * - opg
     * Use this TIF with a market/limit order type to submit “market on open” (MOO) and “limit on open”
     * (LOO) orders. This order is eligible to execute only in the market opening auction. Any unfilled
     * orders after the open will be cancelled. OPG orders submitted after 9:28am but before 7:00pm ET will
     * be rejected. OPG orders submitted after 7:00pm will be queued and routed to the following day’s
     * opening auction. On open/on close orders are routed to the primary exchange. Such orders do not
     * necessarily execute exactly at 9:30am / 4:00pm ET but execute per the exchange’s auction rules.
     *
     * - cls
     * Use this TIF with a market/limit order type to submit “market on close” (MOC) and “limit on close”
     * (LOC) orders. This order is eligible to execute only in the market closing auction. Any unfilled
     * orders after the close will be cancelled. CLS orders submitted after 3:50pm but before 7:00pm ET
     * will be rejected. CLS orders submitted after 7:00pm will be queued and routed to the following day’s
     * closing auction. Only available with API v2.
     *
     * - ioc
     * An Immediate Or Cancel (IOC) order requires all or part of the order to be executed immediately.
     * Any unfilled portion of the order is canceled. Only available with API v2. Most market makers who
     * receive IOC orders will attempt to fill the order on a principal basis only, and cancel any unfilled
     * balance. On occasion, this can result in the entire order being cancelled if the market maker does
     * not have any existing inventory of the security in question.
     *
     * - fok
     * A Fill or Kill (FOK) order is only executed if the entire order quantity can be filled, otherwise
     * the order is canceled. Only available with API v2.
     */
    public function getTimeInForce(): string
    {
        return $this->timeInForce;
    }

    /**
     * Sets Time in Force.
     * Note: For Crypto Trading, Alpaca supports the following Time-In-Force designations: day, gtc, ioc
     * and fok. OPG and CLS are not supported.
     *
     * Alpaca supports the following Time-In-Force designations:
     *
     * - day
     * A day order is eligible for execution only on the day it is live. By default, the order is only
     * valid during Regular Trading Hours (9:30am - 4:00pm ET). If unfilled after the closing auction, it
     * is automatically canceled. If submitted after the close, it is queued and submitted the following
     * trading day. However, if marked as eligible for extended hours, the order can also execute during
     * supported extended hours.
     *
     * - gtc
     * The order is good until canceled. Non-marketable GTC limit orders are subject to price adjustments
     * to offset corporate actions affecting the issue. We do not currently support Do Not Reduce(DNR)
     * orders to opt out of such price adjustments.
     *
     * - opg
     * Use this TIF with a market/limit order type to submit “market on open” (MOO) and “limit on open”
     * (LOO) orders. This order is eligible to execute only in the market opening auction. Any unfilled
     * orders after the open will be cancelled. OPG orders submitted after 9:28am but before 7:00pm ET will
     * be rejected. OPG orders submitted after 7:00pm will be queued and routed to the following day’s
     * opening auction. On open/on close orders are routed to the primary exchange. Such orders do not
     * necessarily execute exactly at 9:30am / 4:00pm ET but execute per the exchange’s auction rules.
     *
     * - cls
     * Use this TIF with a market/limit order type to submit “market on close” (MOC) and “limit on close”
     * (LOC) orders. This order is eligible to execute only in the market closing auction. Any unfilled
     * orders after the close will be cancelled. CLS orders submitted after 3:50pm but before 7:00pm ET
     * will be rejected. CLS orders submitted after 7:00pm will be queued and routed to the following day’s
     * closing auction. Only available with API v2.
     *
     * - ioc
     * An Immediate Or Cancel (IOC) order requires all or part of the order to be executed immediately.
     * Any unfilled portion of the order is canceled. Only available with API v2. Most market makers who
     * receive IOC orders will attempt to fill the order on a principal basis only, and cancel any unfilled
     * balance. On occasion, this can result in the entire order being cancelled if the market maker does
     * not have any existing inventory of the security in question.
     *
     * - fok
     * A Fill or Kill (FOK) order is only executed if the entire order quantity can be filled, otherwise
     * the order is canceled. Only available with API v2.
     *
     * @required
     * @maps time_in_force
     * @factory \TraderApiLib\Models\TimeInForce::checkValue
     */
    public function setTimeInForce(string $timeInForce): void
    {
        $this->timeInForce = $timeInForce;
    }

    /**
     * Returns Limit Price.
     * Limit price
     */
    public function getLimitPrice(): ?string
    {
        if (count($this->limitPrice) == 0) {
            return null;
        }
        return $this->limitPrice['value'];
    }

    /**
     * Sets Limit Price.
     * Limit price
     *
     * @maps limit_price
     */
    public function setLimitPrice(?string $limitPrice): void
    {
        $this->limitPrice['value'] = $limitPrice;
    }

    /**
     * Unsets Limit Price.
     * Limit price
     */
    public function unsetLimitPrice(): void
    {
        $this->limitPrice = [];
    }

    /**
     * Returns Stop Price.
     * Stop price
     */
    public function getStopPrice(): ?string
    {
        if (count($this->stopPrice) == 0) {
            return null;
        }
        return $this->stopPrice['value'];
    }

    /**
     * Sets Stop Price.
     * Stop price
     *
     * @maps stop_price
     */
    public function setStopPrice(?string $stopPrice): void
    {
        $this->stopPrice['value'] = $stopPrice;
    }

    /**
     * Unsets Stop Price.
     * Stop price
     */
    public function unsetStopPrice(): void
    {
        $this->stopPrice = [];
    }

    /**
     * Returns Status.
     * An order executed through Alpaca can experience several status changes during its lifecycle. The
     * most common statuses are described in detail below:
     *
     * - new
     * The order has been received by Alpaca, and routed to exchanges for execution. This is the usual
     * initial state of an order.
     *
     * - partially_filled
     * The order has been partially filled.
     *
     * - filled
     * The order has been filled, and no further updates will occur for the order.
     *
     * - done_for_day
     * The order is done executing for the day, and will not receive further updates until the next
     * trading day.
     *
     * - canceled
     * The order has been canceled, and no further updates will occur for the order. This can be either
     * due to a cancel request by the user, or the order has been canceled by the exchanges due to its time-
     * in-force.
     *
     * - expired
     * The order has expired, and no further updates will occur for the order.
     *
     * - replaced
     * The order was replaced by another order, or was updated due to a market event such as corporate
     * action.
     *
     * - pending_cancel
     * The order is waiting to be canceled.
     *
     * - pending_replace
     * The order is waiting to be replaced by another order. The order will reject cancel request while
     * in this state.
     *
     * Less common states are described below. Note that these states only occur on very rare occasions,
     * and most users will likely never see their orders reach these states:
     *
     * - accepted
     * The order has been received by Alpaca, but hasn’t yet been routed to the execution venue. This
     * could be seen often out side of trading session hours.
     *
     * - pending_new
     * The order has been received by Alpaca, and routed to the exchanges, but has not yet been accepted
     * for execution. This state only occurs on rare occasions.
     *
     * - accepted_for_bidding
     * The order has been received by exchanges, and is evaluated for pricing. This state only occurs on
     * rare occasions.
     *
     * - stopped
     * The order has been stopped, and a trade is guaranteed for the order, usually at a stated price or
     * better, but has not yet occurred. This state only occurs on rare occasions.
     *
     * - rejected
     * The order has been rejected, and no further updates will occur for the order. This state occurs on
     * rare occasions and may occur based on various conditions decided by the exchanges.
     *
     * - suspended
     * The order has been suspended, and is not eligible for trading. This state only occurs on rare
     * occasions.
     *
     * - calculated
     * The order has been completed for the day (either filled or done for day), but remaining settlement
     * calculations are still pending. This state only occurs on rare occasions.
     *
     *
     * An order may be canceled through the API up until the point it reaches a state of either filled,
     * canceled, or expired.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * An order executed through Alpaca can experience several status changes during its lifecycle. The
     * most common statuses are described in detail below:
     *
     * - new
     * The order has been received by Alpaca, and routed to exchanges for execution. This is the usual
     * initial state of an order.
     *
     * - partially_filled
     * The order has been partially filled.
     *
     * - filled
     * The order has been filled, and no further updates will occur for the order.
     *
     * - done_for_day
     * The order is done executing for the day, and will not receive further updates until the next
     * trading day.
     *
     * - canceled
     * The order has been canceled, and no further updates will occur for the order. This can be either
     * due to a cancel request by the user, or the order has been canceled by the exchanges due to its time-
     * in-force.
     *
     * - expired
     * The order has expired, and no further updates will occur for the order.
     *
     * - replaced
     * The order was replaced by another order, or was updated due to a market event such as corporate
     * action.
     *
     * - pending_cancel
     * The order is waiting to be canceled.
     *
     * - pending_replace
     * The order is waiting to be replaced by another order. The order will reject cancel request while
     * in this state.
     *
     * Less common states are described below. Note that these states only occur on very rare occasions,
     * and most users will likely never see their orders reach these states:
     *
     * - accepted
     * The order has been received by Alpaca, but hasn’t yet been routed to the execution venue. This
     * could be seen often out side of trading session hours.
     *
     * - pending_new
     * The order has been received by Alpaca, and routed to the exchanges, but has not yet been accepted
     * for execution. This state only occurs on rare occasions.
     *
     * - accepted_for_bidding
     * The order has been received by exchanges, and is evaluated for pricing. This state only occurs on
     * rare occasions.
     *
     * - stopped
     * The order has been stopped, and a trade is guaranteed for the order, usually at a stated price or
     * better, but has not yet occurred. This state only occurs on rare occasions.
     *
     * - rejected
     * The order has been rejected, and no further updates will occur for the order. This state occurs on
     * rare occasions and may occur based on various conditions decided by the exchanges.
     *
     * - suspended
     * The order has been suspended, and is not eligible for trading. This state only occurs on rare
     * occasions.
     *
     * - calculated
     * The order has been completed for the day (either filled or done for day), but remaining settlement
     * calculations are still pending. This state only occurs on rare occasions.
     *
     *
     * An order may be canceled through the API up until the point it reaches a state of either filled,
     * canceled, or expired.
     *
     * @maps status
     * @factory \TraderApiLib\Models\OrderStatus::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Extended Hours.
     * If true, eligible for execution outside regular trading hours.
     */
    public function getExtendedHours(): ?bool
    {
        return $this->extendedHours;
    }

    /**
     * Sets Extended Hours.
     * If true, eligible for execution outside regular trading hours.
     *
     * @maps extended_hours
     */
    public function setExtendedHours(?bool $extendedHours): void
    {
        $this->extendedHours = $extendedHours;
    }

    /**
     * Returns Legs.
     * When querying non-simple order_class orders in a nested style, an array of Order entities associated
     * with this order. Otherwise, null.
     *
     * @return Order[]|null
     */
    public function getLegs(): ?array
    {
        if (count($this->legs) == 0) {
            return null;
        }
        return $this->legs['value'];
    }

    /**
     * Sets Legs.
     * When querying non-simple order_class orders in a nested style, an array of Order entities associated
     * with this order. Otherwise, null.
     *
     * @maps legs
     *
     * @param Order[]|null $legs
     */
    public function setLegs(?array $legs): void
    {
        $this->legs['value'] = $legs;
    }

    /**
     * Unsets Legs.
     * When querying non-simple order_class orders in a nested style, an array of Order entities associated
     * with this order. Otherwise, null.
     */
    public function unsetLegs(): void
    {
        $this->legs = [];
    }

    /**
     * Returns Trail Percent.
     * The percent value away from the high water mark for trailing stop orders.
     */
    public function getTrailPercent(): ?string
    {
        return $this->trailPercent;
    }

    /**
     * Sets Trail Percent.
     * The percent value away from the high water mark for trailing stop orders.
     *
     * @maps trail_percent
     */
    public function setTrailPercent(?string $trailPercent): void
    {
        $this->trailPercent = $trailPercent;
    }

    /**
     * Returns Trail Price.
     * The dollar value away from the high water mark for trailing stop orders.
     */
    public function getTrailPrice(): ?string
    {
        return $this->trailPrice;
    }

    /**
     * Sets Trail Price.
     * The dollar value away from the high water mark for trailing stop orders.
     *
     * @maps trail_price
     */
    public function setTrailPrice(?string $trailPrice): void
    {
        $this->trailPrice = $trailPrice;
    }

    /**
     * Returns Hwm.
     * The highest (lowest) market price seen since the trailing stop order was submitted.
     */
    public function getHwm(): ?string
    {
        return $this->hwm;
    }

    /**
     * Sets Hwm.
     * The highest (lowest) market price seen since the trailing stop order was submitted.
     *
     * @maps hwm
     */
    public function setHwm(?string $hwm): void
    {
        $this->hwm = $hwm;
    }

    /**
     * Converts the Order object to a human-readable string representation.
     *
     * @return string The string representation of the Order object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Order',
            [
                'id' => $this->id,
                'clientOrderId' => $this->clientOrderId,
                'createdAt' => $this->createdAt,
                'updatedAt' => $this->getUpdatedAt(),
                'submittedAt' => $this->getSubmittedAt(),
                'filledAt' => $this->getFilledAt(),
                'expiredAt' => $this->getExpiredAt(),
                'canceledAt' => $this->getCanceledAt(),
                'failedAt' => $this->getFailedAt(),
                'replacedAt' => $this->getReplacedAt(),
                'replacedBy' => $this->getReplacedBy(),
                'replaces' => $this->getReplaces(),
                'assetId' => $this->assetId,
                'symbol' => $this->symbol,
                'assetClass' => $this->assetClass,
                'notional' => $this->notional,
                'qty' => $this->qty,
                'filledQty' => $this->filledQty,
                'filledAvgPrice' => $this->getFilledAvgPrice(),
                'orderClass' => $this->orderClass,
                'orderType' => $this->orderType,
                'type' => $this->type,
                'side' => $this->side,
                'timeInForce' => $this->timeInForce,
                'limitPrice' => $this->getLimitPrice(),
                'stopPrice' => $this->getStopPrice(),
                'status' => $this->status,
                'extendedHours' => $this->extendedHours,
                'legs' => $this->getLegs(),
                'trailPercent' => $this->trailPercent,
                'trailPrice' => $this->trailPrice,
                'hwm' => $this->hwm,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'client_order_id',
        'created_at',
        'updated_at',
        'submitted_at',
        'filled_at',
        'expired_at',
        'canceled_at',
        'failed_at',
        'replaced_at',
        'replaced_by',
        'replaces',
        'asset_id',
        'symbol',
        'asset_class',
        'notional',
        'qty',
        'filled_qty',
        'filled_avg_price',
        'order_class',
        'order_type',
        'type',
        'side',
        'time_in_force',
        'limit_price',
        'stop_price',
        'status',
        'extended_hours',
        'legs',
        'trail_percent',
        'trail_price',
        'hwm'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->clientOrderId)) {
            $json['client_order_id']  = $this->clientOrderId;
        }
        if (isset($this->createdAt)) {
            $json['created_at']       = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        }
        if (!empty($this->updatedAt)) {
            $json['updated_at']       = DateTimeHelper::toRfc3339DateTime($this->updatedAt['value']);
        }
        if (!empty($this->submittedAt)) {
            $json['submitted_at']     = DateTimeHelper::toRfc3339DateTime($this->submittedAt['value']);
        }
        if (!empty($this->filledAt)) {
            $json['filled_at']        = DateTimeHelper::toRfc3339DateTime($this->filledAt['value']);
        }
        if (!empty($this->expiredAt)) {
            $json['expired_at']       = DateTimeHelper::toRfc3339DateTime($this->expiredAt['value']);
        }
        if (!empty($this->canceledAt)) {
            $json['canceled_at']      = DateTimeHelper::toRfc3339DateTime($this->canceledAt['value']);
        }
        if (!empty($this->failedAt)) {
            $json['failed_at']        = DateTimeHelper::toRfc3339DateTime($this->failedAt['value']);
        }
        if (!empty($this->replacedAt)) {
            $json['replaced_at']      = DateTimeHelper::toRfc3339DateTime($this->replacedAt['value']);
        }
        if (!empty($this->replacedBy)) {
            $json['replaced_by']      = $this->replacedBy['value'];
        }
        if (!empty($this->replaces)) {
            $json['replaces']         = $this->replaces['value'];
        }
        if (isset($this->assetId)) {
            $json['asset_id']         = $this->assetId;
        }
        $json['symbol']               = $this->symbol;
        if (isset($this->assetClass)) {
            $json['asset_class']      = AssetClass::checkValue($this->assetClass);
        }
        $json['notional']             = $this->notional;
        $json['qty']                  = $this->qty;
        if (isset($this->filledQty)) {
            $json['filled_qty']       = $this->filledQty;
        }
        if (!empty($this->filledAvgPrice)) {
            $json['filled_avg_price'] = $this->filledAvgPrice['value'];
        }
        if (isset($this->orderClass)) {
            $json['order_class']      = OrderClass::checkValue($this->orderClass);
        }
        if (isset($this->orderType)) {
            $json['order_type']       = $this->orderType;
        }
        $json['type']                 = OrderType::checkValue($this->type);
        $json['side']                 = OrderSide::checkValue($this->side);
        $json['time_in_force']        = TimeInForce::checkValue($this->timeInForce);
        if (!empty($this->limitPrice)) {
            $json['limit_price']      = $this->limitPrice['value'];
        }
        if (!empty($this->stopPrice)) {
            $json['stop_price']       = $this->stopPrice['value'];
        }
        if (isset($this->status)) {
            $json['status']           = OrderStatus::checkValue($this->status);
        }
        if (isset($this->extendedHours)) {
            $json['extended_hours']   = $this->extendedHours;
        }
        if (!empty($this->legs)) {
            $json['legs']             = $this->legs['value'];
        }
        if (isset($this->trailPercent)) {
            $json['trail_percent']    = $this->trailPercent;
        }
        if (isset($this->trailPrice)) {
            $json['trail_price']      = $this->trailPrice;
        }
        if (isset($this->hwm)) {
            $json['hwm']              = $this->hwm;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
