<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Represents the types of orders Alpaca currently supports
 *
 * - market
 * - limit
 * - stop
 * - stop_limit
 * - trailing_stop
 */
class OrderType
{
    public const MARKET = 'market';

    public const LIMIT = 'limit';

    public const STOP = 'stop';

    public const STOP_LIMIT = 'stop_limit';

    public const TRAILING_STOP = 'trailing_stop';

    private const _ALL_VALUES = [self::MARKET, self::LIMIT, self::STOP, self::STOP_LIMIT, self::TRAILING_STOP];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OrderType.");
    }
}
