<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

/**
 * Represents a request to patch an order.
 */
class PatchOrderRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $qty;

    /**
     * @var string|null
     */
    private $timeInForce;

    /**
     * @var string|null
     */
    private $limitPrice;

    /**
     * @var string|null
     */
    private $stopPrice;

    /**
     * @var string|null
     */
    private $trail;

    /**
     * @var string|null
     */
    private $clientOrderId;

    /**
     * Returns Qty.
     * number of shares to trade
     */
    public function getQty(): ?string
    {
        return $this->qty;
    }

    /**
     * Sets Qty.
     * number of shares to trade
     *
     * @maps qty
     */
    public function setQty(?string $qty): void
    {
        $this->qty = $qty;
    }

    /**
     * Returns Time in Force.
     * Note: For Crypto Trading, Alpaca supports the following Time-In-Force designations: day, gtc, ioc
     * and fok. OPG and CLS are not supported.
     *
     * Alpaca supports the following Time-In-Force designations:
     *
     * - day
     * A day order is eligible for execution only on the day it is live. By default, the order is only
     * valid during Regular Trading Hours (9:30am - 4:00pm ET). If unfilled after the closing auction, it
     * is automatically canceled. If submitted after the close, it is queued and submitted the following
     * trading day. However, if marked as eligible for extended hours, the order can also execute during
     * supported extended hours.
     *
     * - gtc
     * The order is good until canceled. Non-marketable GTC limit orders are subject to price adjustments
     * to offset corporate actions affecting the issue. We do not currently support Do Not Reduce(DNR)
     * orders to opt out of such price adjustments.
     *
     * - opg
     * Use this TIF with a market/limit order type to submit “market on open” (MOO) and “limit on open”
     * (LOO) orders. This order is eligible to execute only in the market opening auction. Any unfilled
     * orders after the open will be cancelled. OPG orders submitted after 9:28am but before 7:00pm ET will
     * be rejected. OPG orders submitted after 7:00pm will be queued and routed to the following day’s
     * opening auction. On open/on close orders are routed to the primary exchange. Such orders do not
     * necessarily execute exactly at 9:30am / 4:00pm ET but execute per the exchange’s auction rules.
     *
     * - cls
     * Use this TIF with a market/limit order type to submit “market on close” (MOC) and “limit on close”
     * (LOC) orders. This order is eligible to execute only in the market closing auction. Any unfilled
     * orders after the close will be cancelled. CLS orders submitted after 3:50pm but before 7:00pm ET
     * will be rejected. CLS orders submitted after 7:00pm will be queued and routed to the following day’s
     * closing auction. Only available with API v2.
     *
     * - ioc
     * An Immediate Or Cancel (IOC) order requires all or part of the order to be executed immediately.
     * Any unfilled portion of the order is canceled. Only available with API v2. Most market makers who
     * receive IOC orders will attempt to fill the order on a principal basis only, and cancel any unfilled
     * balance. On occasion, this can result in the entire order being cancelled if the market maker does
     * not have any existing inventory of the security in question.
     *
     * - fok
     * A Fill or Kill (FOK) order is only executed if the entire order quantity can be filled, otherwise
     * the order is canceled. Only available with API v2.
     */
    public function getTimeInForce(): ?string
    {
        return $this->timeInForce;
    }

    /**
     * Sets Time in Force.
     * Note: For Crypto Trading, Alpaca supports the following Time-In-Force designations: day, gtc, ioc
     * and fok. OPG and CLS are not supported.
     *
     * Alpaca supports the following Time-In-Force designations:
     *
     * - day
     * A day order is eligible for execution only on the day it is live. By default, the order is only
     * valid during Regular Trading Hours (9:30am - 4:00pm ET). If unfilled after the closing auction, it
     * is automatically canceled. If submitted after the close, it is queued and submitted the following
     * trading day. However, if marked as eligible for extended hours, the order can also execute during
     * supported extended hours.
     *
     * - gtc
     * The order is good until canceled. Non-marketable GTC limit orders are subject to price adjustments
     * to offset corporate actions affecting the issue. We do not currently support Do Not Reduce(DNR)
     * orders to opt out of such price adjustments.
     *
     * - opg
     * Use this TIF with a market/limit order type to submit “market on open” (MOO) and “limit on open”
     * (LOO) orders. This order is eligible to execute only in the market opening auction. Any unfilled
     * orders after the open will be cancelled. OPG orders submitted after 9:28am but before 7:00pm ET will
     * be rejected. OPG orders submitted after 7:00pm will be queued and routed to the following day’s
     * opening auction. On open/on close orders are routed to the primary exchange. Such orders do not
     * necessarily execute exactly at 9:30am / 4:00pm ET but execute per the exchange’s auction rules.
     *
     * - cls
     * Use this TIF with a market/limit order type to submit “market on close” (MOC) and “limit on close”
     * (LOC) orders. This order is eligible to execute only in the market closing auction. Any unfilled
     * orders after the close will be cancelled. CLS orders submitted after 3:50pm but before 7:00pm ET
     * will be rejected. CLS orders submitted after 7:00pm will be queued and routed to the following day’s
     * closing auction. Only available with API v2.
     *
     * - ioc
     * An Immediate Or Cancel (IOC) order requires all or part of the order to be executed immediately.
     * Any unfilled portion of the order is canceled. Only available with API v2. Most market makers who
     * receive IOC orders will attempt to fill the order on a principal basis only, and cancel any unfilled
     * balance. On occasion, this can result in the entire order being cancelled if the market maker does
     * not have any existing inventory of the security in question.
     *
     * - fok
     * A Fill or Kill (FOK) order is only executed if the entire order quantity can be filled, otherwise
     * the order is canceled. Only available with API v2.
     *
     * @maps time_in_force
     * @factory \TraderApiLib\Models\TimeInForce::checkValue
     */
    public function setTimeInForce(?string $timeInForce): void
    {
        $this->timeInForce = $timeInForce;
    }

    /**
     * Returns Limit Price.
     * required if original order type is limit or stop_limit
     */
    public function getLimitPrice(): ?string
    {
        return $this->limitPrice;
    }

    /**
     * Sets Limit Price.
     * required if original order type is limit or stop_limit
     *
     * @maps limit_price
     */
    public function setLimitPrice(?string $limitPrice): void
    {
        $this->limitPrice = $limitPrice;
    }

    /**
     * Returns Stop Price.
     * required if original order type is limit or stop_limit
     */
    public function getStopPrice(): ?string
    {
        return $this->stopPrice;
    }

    /**
     * Sets Stop Price.
     * required if original order type is limit or stop_limit
     *
     * @maps stop_price
     */
    public function setStopPrice(?string $stopPrice): void
    {
        $this->stopPrice = $stopPrice;
    }

    /**
     * Returns Trail.
     * the new value of the trail_price or trail_percent value (works only for type=“trailing_stop”)
     */
    public function getTrail(): ?string
    {
        return $this->trail;
    }

    /**
     * Sets Trail.
     * the new value of the trail_price or trail_percent value (works only for type=“trailing_stop”)
     *
     * @maps trail
     */
    public function setTrail(?string $trail): void
    {
        $this->trail = $trail;
    }

    /**
     * Returns Client Order Id.
     * A unique identifier for the order. Automatically generated if not sent.
     */
    public function getClientOrderId(): ?string
    {
        return $this->clientOrderId;
    }

    /**
     * Sets Client Order Id.
     * A unique identifier for the order. Automatically generated if not sent.
     *
     * @maps client_order_id
     */
    public function setClientOrderId(?string $clientOrderId): void
    {
        $this->clientOrderId = $clientOrderId;
    }

    /**
     * Converts the PatchOrderRequest object to a human-readable string representation.
     *
     * @return string The string representation of the PatchOrderRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PatchOrderRequest',
            [
                'qty' => $this->qty,
                'timeInForce' => $this->timeInForce,
                'limitPrice' => $this->limitPrice,
                'stopPrice' => $this->stopPrice,
                'trail' => $this->trail,
                'clientOrderId' => $this->clientOrderId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['qty', 'time_in_force', 'limit_price', 'stop_price', 'trail', 'client_order_id'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->qty)) {
            $json['qty']             = $this->qty;
        }
        if (isset($this->timeInForce)) {
            $json['time_in_force']   = TimeInForce::checkValue($this->timeInForce);
        }
        if (isset($this->limitPrice)) {
            $json['limit_price']     = $this->limitPrice;
        }
        if (isset($this->stopPrice)) {
            $json['stop_price']      = $this->stopPrice;
        }
        if (isset($this->trail)) {
            $json['trail']           = $this->trail;
        }
        if (isset($this->clientOrderId)) {
            $json['client_order_id'] = $this->clientOrderId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
