<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

class PortfolioHistory implements \JsonSerializable
{
    /**
     * @var int[]|null
     */
    private $timestamp;

    /**
     * @var float[]|null
     */
    private $equity;

    /**
     * @var float[]|null
     */
    private $profitLoss;

    /**
     * @var float[]|null
     */
    private $profitLossPct;

    /**
     * @var float|null
     */
    private $baseValue;

    /**
     * @var string|null
     */
    private $timeframe;

    /**
     * Returns Timestamp.
     * time of each data element, left-labeled (the beginning of time window)
     *
     * @return int[]|null
     */
    public function getTimestamp(): ?array
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     * time of each data element, left-labeled (the beginning of time window)
     *
     * @maps timestamp
     *
     * @param int[]|null $timestamp
     */
    public function setTimestamp(?array $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Equity.
     * equity value of the account in dollar amount as of the end of each time window
     *
     * @return float[]|null
     */
    public function getEquity(): ?array
    {
        return $this->equity;
    }

    /**
     * Sets Equity.
     * equity value of the account in dollar amount as of the end of each time window
     *
     * @maps equity
     *
     * @param float[]|null $equity
     */
    public function setEquity(?array $equity): void
    {
        $this->equity = $equity;
    }

    /**
     * Returns Profit Loss.
     * profit/loss in dollar from the base value
     *
     * @return float[]|null
     */
    public function getProfitLoss(): ?array
    {
        return $this->profitLoss;
    }

    /**
     * Sets Profit Loss.
     * profit/loss in dollar from the base value
     *
     * @maps profit_loss
     *
     * @param float[]|null $profitLoss
     */
    public function setProfitLoss(?array $profitLoss): void
    {
        $this->profitLoss = $profitLoss;
    }

    /**
     * Returns Profit Loss Pct.
     * profit/loss in percentage from the base value
     *
     * @return float[]|null
     */
    public function getProfitLossPct(): ?array
    {
        return $this->profitLossPct;
    }

    /**
     * Sets Profit Loss Pct.
     * profit/loss in percentage from the base value
     *
     * @maps profit_loss_pct
     *
     * @param float[]|null $profitLossPct
     */
    public function setProfitLossPct(?array $profitLossPct): void
    {
        $this->profitLossPct = $profitLossPct;
    }

    /**
     * Returns Base Value.
     * basis in dollar of the profit loss calculation
     */
    public function getBaseValue(): ?float
    {
        return $this->baseValue;
    }

    /**
     * Sets Base Value.
     * basis in dollar of the profit loss calculation
     *
     * @maps base_value
     */
    public function setBaseValue(?float $baseValue): void
    {
        $this->baseValue = $baseValue;
    }

    /**
     * Returns Timeframe.
     * time window size of each data element
     */
    public function getTimeframe(): ?string
    {
        return $this->timeframe;
    }

    /**
     * Sets Timeframe.
     * time window size of each data element
     *
     * @maps timeframe
     */
    public function setTimeframe(?string $timeframe): void
    {
        $this->timeframe = $timeframe;
    }

    /**
     * Converts the PortfolioHistory object to a human-readable string representation.
     *
     * @return string The string representation of the PortfolioHistory object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PortfolioHistory',
            [
                'timestamp' => $this->timestamp,
                'equity' => $this->equity,
                'profitLoss' => $this->profitLoss,
                'profitLossPct' => $this->profitLossPct,
                'baseValue' => $this->baseValue,
                'timeframe' => $this->timeframe,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['timestamp', 'equity', 'profit_loss', 'profit_loss_pct', 'base_value', 'timeframe'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->timestamp)) {
            $json['timestamp']       = $this->timestamp;
        }
        if (isset($this->equity)) {
            $json['equity']          = $this->equity;
        }
        if (isset($this->profitLoss)) {
            $json['profit_loss']     = $this->profitLoss;
        }
        if (isset($this->profitLossPct)) {
            $json['profit_loss_pct'] = $this->profitLossPct;
        }
        if (isset($this->baseValue)) {
            $json['base_value']      = $this->baseValue;
        }
        if (isset($this->timeframe)) {
            $json['timeframe']       = $this->timeframe;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
