<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

/**
 * The positions API provides information about an account’s current open positions. The response will
 * include information such as cost basis, shares traded, and market value, which will be updated live
 * as price information is updated. Once a position is closed, it will no longer be queryable through
 * this API.
 */
class Position implements \JsonSerializable
{
    /**
     * @var string
     */
    private $assetId;

    /**
     * @var string
     */
    private $symbol;

    /**
     * @var string
     */
    private $exchange;

    /**
     * @var string
     */
    private $assetClass;

    /**
     * @var string
     */
    private $avgEntryPrice;

    /**
     * @var string
     */
    private $qty;

    /**
     * @var string|null
     */
    private $qtyAvailable;

    /**
     * @var string
     */
    private $side;

    /**
     * @var string
     */
    private $marketValue;

    /**
     * @var string
     */
    private $costBasis;

    /**
     * @var string
     */
    private $unrealizedPl;

    /**
     * @var string
     */
    private $unrealizedPlpc;

    /**
     * @var string
     */
    private $unrealizedIntradayPl;

    /**
     * @var string
     */
    private $unrealizedIntradayPlpc;

    /**
     * @var string
     */
    private $currentPrice;

    /**
     * @var string
     */
    private $lastdayPrice;

    /**
     * @var string
     */
    private $changeToday;

    /**
     * @var bool
     */
    private $assetMarginable;

    /**
     * @param string $assetId
     * @param string $symbol
     * @param string $exchange
     * @param string $assetClass
     * @param string $avgEntryPrice
     * @param string $qty
     * @param string $side
     * @param string $marketValue
     * @param string $costBasis
     * @param string $unrealizedPl
     * @param string $unrealizedPlpc
     * @param string $unrealizedIntradayPl
     * @param string $unrealizedIntradayPlpc
     * @param string $currentPrice
     * @param string $lastdayPrice
     * @param string $changeToday
     * @param bool $assetMarginable
     */
    public function __construct(
        string $assetId,
        string $symbol,
        string $exchange,
        string $assetClass,
        string $avgEntryPrice,
        string $qty,
        string $side,
        string $marketValue,
        string $costBasis,
        string $unrealizedPl,
        string $unrealizedPlpc,
        string $unrealizedIntradayPl,
        string $unrealizedIntradayPlpc,
        string $currentPrice,
        string $lastdayPrice,
        string $changeToday,
        bool $assetMarginable
    ) {
        $this->assetId = $assetId;
        $this->symbol = $symbol;
        $this->exchange = $exchange;
        $this->assetClass = $assetClass;
        $this->avgEntryPrice = $avgEntryPrice;
        $this->qty = $qty;
        $this->side = $side;
        $this->marketValue = $marketValue;
        $this->costBasis = $costBasis;
        $this->unrealizedPl = $unrealizedPl;
        $this->unrealizedPlpc = $unrealizedPlpc;
        $this->unrealizedIntradayPl = $unrealizedIntradayPl;
        $this->unrealizedIntradayPlpc = $unrealizedIntradayPlpc;
        $this->currentPrice = $currentPrice;
        $this->lastdayPrice = $lastdayPrice;
        $this->changeToday = $changeToday;
        $this->assetMarginable = $assetMarginable;
    }

    /**
     * Returns Asset Id.
     * Asset ID
     */
    public function getAssetId(): string
    {
        return $this->assetId;
    }

    /**
     * Sets Asset Id.
     * Asset ID
     *
     * @required
     * @maps asset_id
     */
    public function setAssetId(string $assetId): void
    {
        $this->assetId = $assetId;
    }

    /**
     * Returns Symbol.
     * Symbol name of the asset
     */
    public function getSymbol(): string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * Symbol name of the asset
     *
     * @required
     * @maps symbol
     */
    public function setSymbol(string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Exchange.
     * Represents the current exchanges Alpaca supports. List is currently:
     *
     * - AMEX
     * - ARCA
     * - BATS
     * - NYSE
     * - NASDAQ
     * - NYSEARCA
     * - OTC
     */
    public function getExchange(): string
    {
        return $this->exchange;
    }

    /**
     * Sets Exchange.
     * Represents the current exchanges Alpaca supports. List is currently:
     *
     * - AMEX
     * - ARCA
     * - BATS
     * - NYSE
     * - NASDAQ
     * - NYSEARCA
     * - OTC
     *
     * @required
     * @maps exchange
     * @factory \TraderApiLib\Models\Exchange::checkValue
     */
    public function setExchange(string $exchange): void
    {
        $this->exchange = $exchange;
    }

    /**
     * Returns Asset Class.
     * Represents what class of asset this is. Currently only supports `us_equity` or `crypto`
     */
    public function getAssetClass(): string
    {
        return $this->assetClass;
    }

    /**
     * Sets Asset Class.
     * Represents what class of asset this is. Currently only supports `us_equity` or `crypto`
     *
     * @required
     * @maps asset_class
     * @factory \TraderApiLib\Models\AssetClass::checkValue
     */
    public function setAssetClass(string $assetClass): void
    {
        $this->assetClass = $assetClass;
    }

    /**
     * Returns Avg Entry Price.
     * Average entry price of the position
     */
    public function getAvgEntryPrice(): string
    {
        return $this->avgEntryPrice;
    }

    /**
     * Sets Avg Entry Price.
     * Average entry price of the position
     *
     * @required
     * @maps avg_entry_price
     */
    public function setAvgEntryPrice(string $avgEntryPrice): void
    {
        $this->avgEntryPrice = $avgEntryPrice;
    }

    /**
     * Returns Qty.
     * The number of shares
     */
    public function getQty(): string
    {
        return $this->qty;
    }

    /**
     * Sets Qty.
     * The number of shares
     *
     * @required
     * @maps qty
     */
    public function setQty(string $qty): void
    {
        $this->qty = $qty;
    }

    /**
     * Returns Qty Available.
     * Total number of shares available minus open orders
     */
    public function getQtyAvailable(): ?string
    {
        return $this->qtyAvailable;
    }

    /**
     * Sets Qty Available.
     * Total number of shares available minus open orders
     *
     * @maps qty_available
     */
    public function setQtyAvailable(?string $qtyAvailable): void
    {
        $this->qtyAvailable = $qtyAvailable;
    }

    /**
     * Returns Side.
     * “long”
     */
    public function getSide(): string
    {
        return $this->side;
    }

    /**
     * Sets Side.
     * “long”
     *
     * @required
     * @maps side
     */
    public function setSide(string $side): void
    {
        $this->side = $side;
    }

    /**
     * Returns Market Value.
     * Total dollar amount of the position
     */
    public function getMarketValue(): string
    {
        return $this->marketValue;
    }

    /**
     * Sets Market Value.
     * Total dollar amount of the position
     *
     * @required
     * @maps market_value
     */
    public function setMarketValue(string $marketValue): void
    {
        $this->marketValue = $marketValue;
    }

    /**
     * Returns Cost Basis.
     * Total cost basis in dollar
     */
    public function getCostBasis(): string
    {
        return $this->costBasis;
    }

    /**
     * Sets Cost Basis.
     * Total cost basis in dollar
     *
     * @required
     * @maps cost_basis
     */
    public function setCostBasis(string $costBasis): void
    {
        $this->costBasis = $costBasis;
    }

    /**
     * Returns Unrealized Pl.
     * Unrealized profit/loss in dollars
     */
    public function getUnrealizedPl(): string
    {
        return $this->unrealizedPl;
    }

    /**
     * Sets Unrealized Pl.
     * Unrealized profit/loss in dollars
     *
     * @required
     * @maps unrealized_pl
     */
    public function setUnrealizedPl(string $unrealizedPl): void
    {
        $this->unrealizedPl = $unrealizedPl;
    }

    /**
     * Returns Unrealized Plpc.
     * Unrealized profit/loss percent (by a factor of 1)
     */
    public function getUnrealizedPlpc(): string
    {
        return $this->unrealizedPlpc;
    }

    /**
     * Sets Unrealized Plpc.
     * Unrealized profit/loss percent (by a factor of 1)
     *
     * @required
     * @maps unrealized_plpc
     */
    public function setUnrealizedPlpc(string $unrealizedPlpc): void
    {
        $this->unrealizedPlpc = $unrealizedPlpc;
    }

    /**
     * Returns Unrealized Intraday Pl.
     * Unrealized profit/loss in dollars for the day
     */
    public function getUnrealizedIntradayPl(): string
    {
        return $this->unrealizedIntradayPl;
    }

    /**
     * Sets Unrealized Intraday Pl.
     * Unrealized profit/loss in dollars for the day
     *
     * @required
     * @maps unrealized_intraday_pl
     */
    public function setUnrealizedIntradayPl(string $unrealizedIntradayPl): void
    {
        $this->unrealizedIntradayPl = $unrealizedIntradayPl;
    }

    /**
     * Returns Unrealized Intraday Plpc.
     * Unrealized profit/loss percent (by a factor of 1)
     */
    public function getUnrealizedIntradayPlpc(): string
    {
        return $this->unrealizedIntradayPlpc;
    }

    /**
     * Sets Unrealized Intraday Plpc.
     * Unrealized profit/loss percent (by a factor of 1)
     *
     * @required
     * @maps unrealized_intraday_plpc
     */
    public function setUnrealizedIntradayPlpc(string $unrealizedIntradayPlpc): void
    {
        $this->unrealizedIntradayPlpc = $unrealizedIntradayPlpc;
    }

    /**
     * Returns Current Price.
     * Current asset price per share
     */
    public function getCurrentPrice(): string
    {
        return $this->currentPrice;
    }

    /**
     * Sets Current Price.
     * Current asset price per share
     *
     * @required
     * @maps current_price
     */
    public function setCurrentPrice(string $currentPrice): void
    {
        $this->currentPrice = $currentPrice;
    }

    /**
     * Returns Lastday Price.
     * Last day’s asset price per share based on the closing value of the last trading day
     */
    public function getLastdayPrice(): string
    {
        return $this->lastdayPrice;
    }

    /**
     * Sets Lastday Price.
     * Last day’s asset price per share based on the closing value of the last trading day
     *
     * @required
     * @maps lastday_price
     */
    public function setLastdayPrice(string $lastdayPrice): void
    {
        $this->lastdayPrice = $lastdayPrice;
    }

    /**
     * Returns Change Today.
     * Percent change from last day price (by a factor of 1)
     */
    public function getChangeToday(): string
    {
        return $this->changeToday;
    }

    /**
     * Sets Change Today.
     * Percent change from last day price (by a factor of 1)
     *
     * @required
     * @maps change_today
     */
    public function setChangeToday(string $changeToday): void
    {
        $this->changeToday = $changeToday;
    }

    /**
     * Returns Asset Marginable.
     */
    public function getAssetMarginable(): bool
    {
        return $this->assetMarginable;
    }

    /**
     * Sets Asset Marginable.
     *
     * @required
     * @maps asset_marginable
     */
    public function setAssetMarginable(bool $assetMarginable): void
    {
        $this->assetMarginable = $assetMarginable;
    }

    /**
     * Converts the Position object to a human-readable string representation.
     *
     * @return string The string representation of the Position object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Position',
            [
                'assetId' => $this->assetId,
                'symbol' => $this->symbol,
                'exchange' => $this->exchange,
                'assetClass' => $this->assetClass,
                'avgEntryPrice' => $this->avgEntryPrice,
                'qty' => $this->qty,
                'qtyAvailable' => $this->qtyAvailable,
                'side' => $this->side,
                'marketValue' => $this->marketValue,
                'costBasis' => $this->costBasis,
                'unrealizedPl' => $this->unrealizedPl,
                'unrealizedPlpc' => $this->unrealizedPlpc,
                'unrealizedIntradayPl' => $this->unrealizedIntradayPl,
                'unrealizedIntradayPlpc' => $this->unrealizedIntradayPlpc,
                'currentPrice' => $this->currentPrice,
                'lastdayPrice' => $this->lastdayPrice,
                'changeToday' => $this->changeToday,
                'assetMarginable' => $this->assetMarginable,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'asset_id',
        'symbol',
        'exchange',
        'asset_class',
        'avg_entry_price',
        'qty',
        'qty_available',
        'side',
        'market_value',
        'cost_basis',
        'unrealized_pl',
        'unrealized_plpc',
        'unrealized_intraday_pl',
        'unrealized_intraday_plpc',
        'current_price',
        'lastday_price',
        'change_today',
        'asset_marginable'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['asset_id']                 = $this->assetId;
        $json['symbol']                   = $this->symbol;
        $json['exchange']                 = Exchange::checkValue($this->exchange);
        $json['asset_class']              = AssetClass::checkValue($this->assetClass);
        $json['avg_entry_price']          = $this->avgEntryPrice;
        $json['qty']                      = $this->qty;
        if (isset($this->qtyAvailable)) {
            $json['qty_available']        = $this->qtyAvailable;
        }
        $json['side']                     = $this->side;
        $json['market_value']             = $this->marketValue;
        $json['cost_basis']               = $this->costBasis;
        $json['unrealized_pl']            = $this->unrealizedPl;
        $json['unrealized_plpc']          = $this->unrealizedPlpc;
        $json['unrealized_intraday_pl']   = $this->unrealizedIntradayPl;
        $json['unrealized_intraday_plpc'] = $this->unrealizedIntradayPlpc;
        $json['current_price']            = $this->currentPrice;
        $json['lastday_price']            = $this->lastdayPrice;
        $json['change_today']             = $this->changeToday;
        $json['asset_marginable']         = $this->assetMarginable;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
