<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

/**
 * Represents the result of asking the api to close a position.
 */
class PositionClosedReponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $symbol;

    /**
     * @var string
     */
    private $status;

    /**
     * @var Order|null
     */
    private $body;

    /**
     * @param string $symbol
     * @param string $status
     */
    public function __construct(string $symbol, string $status)
    {
        $this->symbol = $symbol;
        $this->status = $status;
    }

    /**
     * Returns Symbol.
     * Symbol name of the asset
     */
    public function getSymbol(): string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * Symbol name of the asset
     *
     * @required
     * @maps symbol
     */
    public function setSymbol(string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Status.
     * Http status code for the attempt to close this position
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Http status code for the attempt to close this position
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Body.
     * The Orders API allows a user to monitor, place and cancel their orders with Alpaca.
     *
     * Each order has a unique identifier provided by the client. This client-side unique order ID will be
     * automatically generated by the system if not provided by the client, and will be returned as part of
     * the order object along with the rest of the fields described below. Once an order is placed, it can
     * be queried using the client-side order ID to check the status.
     *
     * Updates on open orders at Alpaca will also be sent over the streaming interface, which is the
     * recommended method of maintaining order state.
     */
    public function getBody(): ?Order
    {
        return $this->body;
    }

    /**
     * Sets Body.
     * The Orders API allows a user to monitor, place and cancel their orders with Alpaca.
     *
     * Each order has a unique identifier provided by the client. This client-side unique order ID will be
     * automatically generated by the system if not provided by the client, and will be returned as part of
     * the order object along with the rest of the fields described below. Once an order is placed, it can
     * be queried using the client-side order ID to check the status.
     *
     * Updates on open orders at Alpaca will also be sent over the streaming interface, which is the
     * recommended method of maintaining order state.
     *
     * @maps body
     */
    public function setBody(?Order $body): void
    {
        $this->body = $body;
    }

    /**
     * Converts the PositionClosedReponse object to a human-readable string representation.
     *
     * @return string The string representation of the PositionClosedReponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PositionClosedReponse',
            [
                'symbol' => $this->symbol,
                'status' => $this->status,
                'body' => $this->body,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['symbol', 'status', 'body'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['symbol']   = $this->symbol;
        $json['status']   = $this->status;
        if (isset($this->body)) {
            $json['body'] = $this->body;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
