<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;

/**
 * Request format used for creating a new watchlist or updating an existing watchlist with a set of
 * assets and name.
 */
class PostWatchlistRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $name;

    /**
     * @var array<string|null>|null
     */
    private $symbols;

    /**
     * @param string $name
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Symbols.
     *
     * @return array<string|null>|null
     */
    public function getSymbols(): ?array
    {
        return $this->symbols;
    }

    /**
     * Sets Symbols.
     *
     * @maps symbols
     *
     * @param array<string|null>|null $symbols
     */
    public function setSymbols(?array $symbols): void
    {
        $this->symbols = $symbols;
    }

    /**
     * Converts the PostWatchlistRequest object to a human-readable string representation.
     *
     * @return string The string representation of the PostWatchlistRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PostWatchlistRequest',
            [
                'name' => $this->name,
                'symbols' => $this->symbols,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['name', 'symbols'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']        = $this->name;
        if (isset($this->symbols)) {
            $json['symbols'] = $this->symbols;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
