<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib\Models;

use stdClass;
use TraderApiLib\ApiHelper;
use TraderApiLib\Utils\DateTimeHelper;

/**
 * The watchlist API provides CRUD operation for the account’s watchlist. An account can have multiple
 * watchlists and each is uniquely identified by id but can also be addressed by user-defined name.
 * Each watchlist is an ordered list of assets.
 */
class Watchlist implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $accountId;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var string
     */
    private $name;

    /**
     * @var Assets[]|null
     */
    private $assets;

    /**
     * @param string $id
     * @param string $accountId
     * @param \DateTime $createdAt
     * @param \DateTime $updatedAt
     * @param string $name
     */
    public function __construct(
        string $id,
        string $accountId,
        \DateTime $createdAt,
        \DateTime $updatedAt,
        string $name
    ) {
        $this->id = $id;
        $this->accountId = $accountId;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->name = $name;
    }

    /**
     * Returns Id.
     * watchlist id
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * watchlist id
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Account Id.
     * account ID
     */
    public function getAccountId(): string
    {
        return $this->accountId;
    }

    /**
     * Sets Account Id.
     * account ID
     *
     * @required
     * @maps account_id
     */
    public function setAccountId(string $accountId): void
    {
        $this->accountId = $accountId;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     * @factory \TraderApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Name.
     * user-defined watchlist name (up to 64 characters)
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * user-defined watchlist name (up to 64 characters)
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Assets.
     * the content of this watchlist, in the order as registered by the client
     *
     * @return Assets[]|null
     */
    public function getAssets(): ?array
    {
        return $this->assets;
    }

    /**
     * Sets Assets.
     * the content of this watchlist, in the order as registered by the client
     *
     * @maps assets
     *
     * @param Assets[]|null $assets
     */
    public function setAssets(?array $assets): void
    {
        $this->assets = $assets;
    }

    /**
     * Converts the Watchlist object to a human-readable string representation.
     *
     * @return string The string representation of the Watchlist object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Watchlist',
            [
                'id' => $this->id,
                'accountId' => $this->accountId,
                'createdAt' => $this->createdAt,
                'updatedAt' => $this->updatedAt,
                'name' => $this->name,
                'assets' => $this->assets,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['id', 'account_id', 'created_at', 'updated_at', 'name', 'assets'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']         = $this->id;
        $json['account_id'] = $this->accountId;
        $json['created_at'] = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        $json['updated_at'] = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        $json['name']       = $this->name;
        if (isset($this->assets)) {
            $json['assets'] = $this->assets;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
