<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib;

use CoreInterfaces\Http\HttpConfigurations;
use TraderApiLib\Authentication\ApiKeyCredentials;
use TraderApiLib\Authentication\ApiKeyCredentialsBuilder;
use TraderApiLib\Authentication\ApiSecretCredentials;
use TraderApiLib\Authentication\ApiSecretCredentialsBuilder;
use TraderApiLib\Logging\LoggingConfigurationBuilder;
use TraderApiLib\Proxy\ProxyConfigurationBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with ApiKey
     */
    public function getApiKeyCredentials(): ApiKeyCredentials;

    /**
     * Get the credentials builder instance to update credentials for ApiKey
     */
    public function getApiKeyCredentialsBuilder(): ?ApiKeyCredentialsBuilder;

    /**
     * Get the credentials to use with ApiSecret
     */
    public function getApiSecretCredentials(): ApiSecretCredentials;

    /**
     * Get the credentials builder instance to update credentials for ApiSecret
     */
    public function getApiSecretCredentialsBuilder(): ?ApiSecretCredentialsBuilder;

    /**
     * Represents the logging configurations for API calls.
     */
    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder;

    /**
     * Represents the proxy configurations for API calls.
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
