<?php

declare(strict_types=1);

/*
 * TraderApi
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Paper trading — simulated money. Safe default.
     */
    public const PAPER = 'Paper';

    /**
     * Live trading — REAL money.
     */
    public const LIVE = 'Live';
}
