<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Paper
     */
    public const PRODUCTION = 'production';

    /**
     * Live
     */
    public const ENVIRONMENT2 = 'environment2';
}
