<?php

declare(strict_types=1);

/*
 * TraderApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TraderApiLib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use TraderApiLib\Apis\AccountActivitiesApi;
use TraderApiLib\Apis\AccountConfigurationsApi;
use TraderApiLib\Apis\AccountsApi;
use TraderApiLib\Apis\CalendarApi;
use TraderApiLib\Apis\ClockApi;
use TraderApiLib\Apis\OrdersApi;
use TraderApiLib\Apis\PortfolioHistoryApi;
use TraderApiLib\Apis\PositionsApi;
use TraderApiLib\Apis\WatchlistsApi;
use TraderApiLib\Authentication\ApiKeyCredentials;
use TraderApiLib\Authentication\ApiKeyCredentialsBuilder;
use TraderApiLib\Authentication\ApiKeyManager;
use TraderApiLib\Authentication\ApiSecretCredentials;
use TraderApiLib\Authentication\ApiSecretCredentialsBuilder;
use TraderApiLib\Authentication\ApiSecretManager;
use TraderApiLib\Logging\LoggingConfigurationBuilder;
use TraderApiLib\Logging\RequestLoggingConfigurationBuilder;
use TraderApiLib\Logging\ResponseLoggingConfigurationBuilder;
use TraderApiLib\Proxy\ProxyConfigurationBuilder;
use TraderApiLib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class TraderApiClient implements ConfigurationInterface
{
    private $accounts;

    private $orders;

    private $positions;

    private $portfolioHistory;

    private $watchlists;

    private $accountConfigurations;

    private $accountActivities;

    private $calendar;

    private $clock;

    private $apiKeyManager;

    private $apiSecretManager;

    private $loggingConfigurationBuilder;

    private $proxyConfiguration;

    private $config;

    private $client;

    /**
     * @see TraderApiClientBuilder::init()
     * @see TraderApiClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->apiKeyManager = new ApiKeyManager($this->config);
        $this->apiSecretManager = new ApiSecretManager($this->config);
        $loggingConfiguration = null;
        if ($this->config['loggingConfiguration'] instanceof LoggingConfigurationBuilder) {
            $this->loggingConfigurationBuilder = $this->config['loggingConfiguration'];
            $loggingConfiguration = $this->loggingConfigurationBuilder->build();
        }
        $this->proxyConfiguration = $this->config['proxyConfiguration'] ?? ConfigurationDefaults::PROXY_CONFIGURATION;
        $this->client = ClientBuilder::init(
            new HttpClient(Configuration::init($this)->proxyConfiguration($this->proxyConfiguration))
        )
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('PHP-SDK/2.0.0 (OS: {os-info}, Engine: {engine}/{engine-version})')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['API_Key' => $this->apiKeyManager, 'API_Secret' => $this->apiSecretManager])
            ->loggingConfiguration($loggingConfiguration)
            ->build();
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return TraderApiClientBuilder TraderApiClientBuilder instance
     */
    public function toBuilder(): TraderApiClientBuilder
    {
        $builder = TraderApiClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null)
            ->proxyConfiguration($this->getProxyConfigurationBuilder());

        $apiKey = $this->getApiKeyCredentialsBuilder();
        if ($apiKey != null) {
            $builder->apiKeyCredentials($apiKey);
        }

        $apiSecret = $this->getApiSecretCredentialsBuilder();
        if ($apiSecret != null) {
            $builder->apiSecretCredentials($apiSecret);
        }
        $loggingConfigurationBuilder = $this->getLoggingConfigurationBuilder();
        if ($loggingConfigurationBuilder != null) {
            $builder->loggingConfiguration($loggingConfigurationBuilder);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getApiKeyCredentials(): ApiKeyCredentials
    {
        return $this->apiKeyManager;
    }

    public function getApiKeyCredentialsBuilder(): ?ApiKeyCredentialsBuilder
    {
        if (empty($this->apiKeyManager->getApcaApiKeyId())) {
            return null;
        }
        return ApiKeyCredentialsBuilder::init($this->apiKeyManager->getApcaApiKeyId());
    }

    public function getApiSecretCredentials(): ApiSecretCredentials
    {
        return $this->apiSecretManager;
    }

    public function getApiSecretCredentialsBuilder(): ?ApiSecretCredentialsBuilder
    {
        if (empty($this->apiSecretManager->getApcaApiSecretKey())) {
            return null;
        }
        return ApiSecretCredentialsBuilder::init($this->apiSecretManager->getApcaApiSecretKey());
    }

    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder
    {
        if (is_null($this->loggingConfigurationBuilder)) {
            return null;
        }
        $config = $this->loggingConfigurationBuilder->getConfiguration();
        return LoggingConfigurationBuilder::init()
            ->level($config['level'])
            ->logger($config['logger'])
            ->maskSensitiveHeaders($config['maskSensitiveHeaders'])
            ->requestConfiguration(RequestLoggingConfigurationBuilder::init()
                ->includeQueryInPath($config['requestConfiguration']['includeQueryInPath'])
                ->body($config['requestConfiguration']['body'])
                ->headers($config['requestConfiguration']['headers'])
                ->includeHeaders(...$config['requestConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['requestConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['requestConfiguration']['unmaskHeaders']))
            ->responseConfiguration(ResponseLoggingConfigurationBuilder::init()
                ->body($config['responseConfiguration']['body'])
                ->headers($config['responseConfiguration']['headers'])
                ->includeHeaders(...$config['responseConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['responseConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['responseConfiguration']['unmaskHeaders']));
    }

    /**
     * Get the proxy configuration builder
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder
    {
        return ProxyConfigurationBuilder::init($this->proxyConfiguration['address'])
            ->port($this->proxyConfiguration['port'])
            ->tunnel($this->proxyConfiguration['tunnel'])
            ->auth($this->proxyConfiguration['auth']['user'], $this->proxyConfiguration['auth']['pass'])
            ->authMethod($this->proxyConfiguration['auth']['method']);
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see TraderApiClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see TraderApiClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Accounts Api
     */
    public function getAccountsApi(): AccountsApi
    {
        if ($this->accounts == null) {
            $this->accounts = new AccountsApi($this->client);
        }
        return $this->accounts;
    }

    /**
     * Returns Orders Api
     */
    public function getOrdersApi(): OrdersApi
    {
        if ($this->orders == null) {
            $this->orders = new OrdersApi($this->client);
        }
        return $this->orders;
    }

    /**
     * Returns Positions Api
     */
    public function getPositionsApi(): PositionsApi
    {
        if ($this->positions == null) {
            $this->positions = new PositionsApi($this->client);
        }
        return $this->positions;
    }

    /**
     * Returns Portfolio History Api
     */
    public function getPortfolioHistoryApi(): PortfolioHistoryApi
    {
        if ($this->portfolioHistory == null) {
            $this->portfolioHistory = new PortfolioHistoryApi($this->client);
        }
        return $this->portfolioHistory;
    }

    /**
     * Returns Watchlists Api
     */
    public function getWatchlistsApi(): WatchlistsApi
    {
        if ($this->watchlists == null) {
            $this->watchlists = new WatchlistsApi($this->client);
        }
        return $this->watchlists;
    }

    /**
     * Returns Account Configurations Api
     */
    public function getAccountConfigurationsApi(): AccountConfigurationsApi
    {
        if ($this->accountConfigurations == null) {
            $this->accountConfigurations = new AccountConfigurationsApi($this->client);
        }
        return $this->accountConfigurations;
    }

    /**
     * Returns Account Activities Api
     */
    public function getAccountActivitiesApi(): AccountActivitiesApi
    {
        if ($this->accountActivities == null) {
            $this->accountActivities = new AccountActivitiesApi($this->client);
        }
        return $this->accountActivities;
    }

    /**
     * Returns Calendar Api
     */
    public function getCalendarApi(): CalendarApi
    {
        if ($this->calendar == null) {
            $this->calendar = new CalendarApi($this->client);
        }
        return $this->calendar;
    }

    /**
     * Returns Clock Api
     */
    public function getClockApi(): ClockApi
    {
        if ($this->clock == null) {
            $this->clock = new ClockApi($this->client);
        }
        return $this->clock;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [Server::DEFAULT_ => 'https://paper-api.alpaca.markets'],
        Environment::ENVIRONMENT2 => [Server::DEFAULT_ => 'https://api.alpaca.markets']
    ];
}
